wip: 79 star component
bitshares/bitshares-community-ui pull request #101
Opened 2018-10-21 06:07 UTC by MindfulMe

#### What's this PR do?
renames the branch from 'star-component' to '79-star-component' also adding useful corrections to Star.vue
#### Where should the reviewer start?
Star.vue
#### How should this be manually tested?

#### Any background context you want to provide?
The star hovers on select, also can be permanently selected from props
#### What are the relevant tickets?
[#79](https://github.com/bitshares/bitshares-community-ui/issues/79)
#### Screenshots (if appropriate)
<img width="88" alt="screen shot 2018-10-16 at 17 53 38" src="https://user-images.githubusercontent.com/26275425/47025978-28be4a00-d16d-11e8-8a32-74abbebd678f.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/79-star-component/#/components
#### Questions:
Hover should be done from CSS or by replacing an icon using js? I had a solution using js.

2018-10-22 11:08 UTC, roma219 commented
@MindfulMe Why did you close preview PR? Now the hover is done ok, but the hover and active state's color are the same...

2018-10-22 11:39 UTC, MindfulMe commented
@roma219 The old PR was closed due to the bad branch name (you noted that in the past, to give branches more appropriate names), also I will make the white color from props and grey from hover while not filled from props, is it ok?

2018-10-23 17:44 UTC, roma219 requested changes
Last change and it's ok

2018-10-23 17:44 UTC, roma219 commented on src/components/Star/Star.vue
> +.defaultActive {
Name classes in the same codestyle, and use better naming that is self explaniatory. It's hard to understand what is  "default active" (default what?). Better name it `is-active`

2018-10-24 04:48 UTC, roma219 commented
@MindfulMe 
![image](https://user-images.githubusercontent.com/4411295/47406885-3a9d7f80-d761-11e8-928e-307b765fef11.png)

2018-10-24 05:57 UTC, roma219 approved these changes

2018-10-24 05:58 UTC, merged