wip: 100 Login screen fixes
bitshares/bitshares-community-ui pull request #105
Opened 2018-10-22 12:25 UTC by MindfulMe

#### What's this PR do?
Applies the other conditional rendering 
#### Where should the reviewer start?
At views/Login/Login.vue
#### How should this be manually tested?
Login via Private Key
#### Any background context you want to provide?
The pin code fields hidden by default, key file input disappears after entering brainkey, password field appears after uploading key file
#### What are the relevant tickets?
#100 
#### Screenshots (if appropriate)
<img width="572" alt="screen shot 2018-10-22 at 15 21 46" src="https://user-images.githubusercontent.com/26275425/47291949-390f7280-d60e-11e8-9e74-4db35d17e0d4.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
http://staging-ui.trusty.apasia.tech:8080/100-login-screen-fixes
#### Questions:
There is a place for @focus and @blur events, should UX be improved using them or this is enough (current conditions for the rendering seem ok too)?

2018-10-29 07:19 UTC, roma219 commented
Doesn't seem to fix everything that is stated in issue. Open when when fixes & ready for review

2018-10-29 15:34 UTC, roma219 commented
@MindfulMe is this WIP or done?

2018-10-29 15:38 UTC, MindfulMe commented
I am working on it right now

2018-10-29 15:39 UTC, MindfulMe commented
@roma219 I will ask for a review in 1 hour

2018-10-29 15:52 UTC, roma219 commented
@MindfulMe Sure, but next time please open PR when it is actually should be reviewed, or it becomes confusing

2018-10-29 16:26 UTC, mindfulme commented
@roma219 got it

2018-10-29 17:27 UTC, mindfulme commented
@roma219 though, by default input field deletes all spaces. So, I am wondering how backup phrase look like? Maybe, it is concatenated words into one big string without whitespaces?

2018-10-29 17:39 UTC, roma219 commented
@MindfulMe It does not delete all spaces, only trims trailing spaces at the end
![image](https://user-images.githubusercontent.com/4411295/47668877-a432e900-dbba-11e8-83b9-1ca265e878cf.png)

2018-10-30 06:46 UTC, roma219 requested changes
Not reviewing the rest since it doesn't work right:
![image](https://user-images.githubusercontent.com/4411295/47700611-2efdfd00-dc28-11e8-8ca2-d08cb9b101a5.png)
No error message about length of brainkey, login button not blocked, keyfile button appeared.

Hint: The whole issue might be too much for you know. I propose you start from scratch and fix just something from the issue, say only 1 point. State what you fixed in PR, i'll review it & merge, and than you can start working on another small thing. You need to understand how the whole validation mechanic works in Login/Signup

2018-10-30 06:46 UTC, roma219 commented on src/views/Login/Login.vue
> +                this.brainkeyCompleted = true
The whole validator can simly be `return value.split(' ').length - 1 >= 15`, no need for additional variables and conditions. You can access validator's valid/invalid state throught `this.$v` object in component (see vuelidate docs for info).

2018-10-30 06:46 UTC, roma219 commented on src/helpers/inputMessages.js
> +      minLength: 'Must contain 16 words'
there is no minlength validator on a brainkey, isn't it?

2018-10-30 21:54 UTC, MindfulMe commented
@roma219 I can cope with it

2018-10-30 22:39 UTC, MindfulMe commented on src/helpers/inputMessages.js
> +      minLength: 'Must contain 16 words'
yep, should be not `brainkeyValidator ` rather `minLength`

2018-10-30 22:40 UTC, MindfulMe commented on src/views/Login/Login.vue
> +                this.brainkeyCompleted = true
I think I can't call then minLength anywhere without passing a parameter `value` to it

2018-10-31 09:23 UTC, roma219 requested changes
Fix what is written in comments before submitting for review again

2018-10-31 09:23 UTC, roma219 commented on src/helpers/inputMessages.js
> +      minLength: 'Must contain 16 words'
MinLength only checks for string length, not applicable to brainkey

2018-10-31 09:23 UTC, roma219 commented on src/views/Login/Login.vue
> +          :disabled="loginDisabled || (!file && !brainkeyCompleted && !password)"
Should not be any other checks here, besides`loginDisabled`, move your condition to that computed value

2018-10-31 09:23 UTC, roma219 commented on src/views/Login/Login.vue
> +                this.brainkeyCompleted = true
> I think I can't call then minLength anywhere without passing a parameter value to it

What it has to do with my comment?

2018-10-31 09:25 UTC, roma219 commented
@MindfulMe Also remove the trimming of the last space by input in brainkey field

2018-10-31 16:09 UTC, MindfulMe commented
@roma219 refactored exactly according to your comments

2018-11-01 15:23 UTC, roma219 commented on src/views/Login/Login.vue
> +            validator: (value) => (value.split(' ').length - 1 >= 15)
It is the same as naming function `function`. You had an ok name before.

2018-11-01 15:25 UTC, roma219 requested changes
Better, needs a few changes. Will check thoughtfully later.

2018-11-01 15:25 UTC, roma219 commented on src/views/Login/Login.vue
> +    onFocus() {
`onFocus` of what? There are several fields in component. Rename it to onBrainkeyInputFocus

2018-11-01 15:25 UTC, roma219 commented on src/views/Login/Login.vue
> +    onBlur() {
Same as onFocus

2018-11-01 18:47 UTC, MindfulMe commented on src/views/Login/Login.vue
> +    onBlur() {
just renamed to onBrainkeyInputBlur

2018-11-01 18:47 UTC, MindfulMe commented on src/views/Login/Login.vue
> +    onFocus() {
just renamed to onBrainkeyInputFocus

2018-11-02 16:44 UTC, roma219 commented
@MindfulMe This is not done:

-show KEY FILE button back when user exits the field (clicks cross or clicks outside)[after brainkey fully entered]
on Signup screen on tab Password change text "Your account will be secured only with password" to --"Faster, but less secure way to Signup. Your account will be secured only with password. Slower way to signup will better protect you"
-with yellow font in the row just under the line of the field Confirm password insert text "This password can't be recovered, write it on paper"
-on Signup screen on tab Private key change text "You need to backup account after creating a PIN code" to "Slower, but more secure way to Signup protects your account with a combination of PIN and Backup phrase. You need to backup account after creating a PIN code"

2018-11-02 18:10 UTC, MindfulMe commented
@roma219 The text has been changed several days ago, the other conditions were completed according to the issue ticket #100. The following will be re-written according to your comment above:

-show KEY FILE button back when the user exits the field (clicks cross or clicks outside)[after brainkey fully entered]

-with yellow font in the row just under the line of the field Confirm password insert text "This password can't be recovered, write it on paper"

2018-11-04 18:55 UTC, roma219 commented
@MindfulMe conflicts, merge latest dev this repo and vuex-bitshares

2018-11-04 18:59 UTC, roma219 requested changes
Needs explanations and fixes

2018-11-04 18:59 UTC, roma219 commented on src/views/Login/Login.vue
> +            brainkeyValidator: (value) => (value.split(' ').length - 1 >= 15)
just `value =>`

2018-11-04 18:59 UTC, roma219 commented on src/helpers/inputMessages.js
> +      sameAsPassword: 'Passwords do not match \n '
Why are you adding `\n`? There is no need for it

2018-11-04 18:59 UTC, roma219 commented on src/views/Login/Login.vue
> +      return (this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password)
What does this condition mean? This should be validated throught vuelidate `validations` config

2018-11-04 20:35 UTC, MindfulMe commented on src/views/Login/Login.vue
> +            brainkeyValidator: (value) => (value.split(' ').length - 1 >= 15)
could be just value - yes

2018-11-04 20:36 UTC, MindfulMe commented on src/views/Login/Login.vue
> +      return (this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password)
I found 3 ways to complete it, okay - I will use vuelidate validations config

2018-11-04 20:40 UTC, MindfulMe commented on src/views/Login/Login.vue
> +            brainkeyValidator: (value) => (value.split(' ').length - 1 >= 15)
thought in `required` could be just value

2018-11-04 20:59 UTC, MindfulMe commented
@roma219 review & merge if ok

2018-11-04 21:03 UTC, roma219 commented
@MindfulMe not ok

2018-11-04 21:07 UTC, roma219 commented
@MindfulMe read this fully first, you need to understand what you are doing
https://monterail.github.io/vuelidate/

2018-11-04 21:07 UTC, roma219 commented on src/views/Login/Login.vue
> +            isLoginDisabled: () => ((this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password))
wtf is this

2018-11-04 21:07 UTC, roma219 commented on src/views/Login/Login.vue
> +            isLoginDisabled: () => ((this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password))
what is this

2018-11-04 21:08 UTC, MindfulMe commented
@roma219 got it

2018-11-04 23:20 UTC, MindfulMe commented
@roma219 I completely misunderstood you, I did a rollback and removed the `this.$v.$dirty && this.$v.$invalid`

2018-11-04 23:23 UTC, mindfulme commented
@roma219 review & merge if ok

2018-11-04 23:48 UTC, MindfulMe commented on src/views/Login/Login.vue
> +            isLoginDisabled: () => ((this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password))
I had the same reaction when I saw you want me to change the validation, the thing was to remove the useless `this.$v.$dirty && this.$v.$invalid` which were here by default

2018-11-04 23:48 UTC, MindfulMe commented on src/views/Login/Login.vue
> +            isLoginDisabled: () => ((this.$v.$dirty && this.$v.$invalid) || (!this.file && !this.$v.brainkey.brainkeyValidator && !this.password))
fixed by the latest commit

2018-11-05 07:30 UTC, roma219 requested changes

2018-11-05 07:30 UTC, roma219 commented on src/views/Login/Login.vue
> -      return this.$v.$dirty && this.$v.$invalid
Why are you removing this? This simply disabled button when vuelidate validation doesn't pass, so this should remain how it was. You need to add your checks to validation configs itself.

2018-11-05 07:31 UTC, roma219 commented
> @roma219 I completely misunderstood you, I did a rollback and removed the `this.$v.$dirty && this.$v.$invalid`

You shouldn't remove it. You need to read through the docs first to understand how it works.

2018-11-05 14:33 UTC, MindfulMe commented
@roma219 I have read thoroughly Vuelidate docs also several posts on Monterail blog.  I have changed the default condition as it was not fully correct, and tested everything - now the button is enabled when required fields are filled & satisfy the requirements

2018-11-05 17:22 UTC, roma219 requested changes
Revert changes with $dirty checking (see comment) and it's good to go

2018-11-05 17:22 UTC, roma219 commented on src/views/Login/Login.vue
> +      return this.$v.$dirty || this.$v.$invalid
It was && for specific reason - to initially show "clean" view without disabled button and only disable it after first validations ( = dirty checking)

2018-11-05 19:17 UTC, MindfulMe commented on src/views/Login/Login.vue
> +      return this.$v.$dirty || this.$v.$invalid
@roma219 done

2018-11-06 06:24 UTC, roma219 approved these changes

2018-11-06 06:25 UTC, merged