104 markets
bitshares/bitshares-community-ui pull request #107
Opened 2018-10-24 16:01 UTC by lapinlapin

#### What's this PR do?
#### Where should the reviewer start?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
#### Questions:

2018-10-25 06:12 UTC, roma219 requested changes
Overall good, but needs some changes.

Main points:
1) expanding/modal window should not be inside widget, but a part of card functionality (so every card can be expanded). When expanded, card should send prop `:expanded="true"` to a widget in slot. So the only thing widget should know if it is in expanded mode or not. 
2) Seach - for now use it in Card's component header slot (will make a better mechanics later with scoped slots)
3) `Star` and `SortableTableItemHeader` components are available in the latest dev branch, use them
4) pull latest dev branch of `vuex-bitshares`
5) Please use rems instead of pixels and use tailwind config file when needed/necessary
6) See comments

2018-10-25 06:12 UTC, roma219 commented on src/store/markets.js
> +  markets(state) {
For better naming, lets name getters starting with `get` (no to confuse it with anything else) and since it is a namespaces module this getter can be named as someting like `getList` so in mapGetters it is gonna be referred as `markets/getList`

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +        class="markets__expanded"
Confusing name, this is the button to expand the widget, right? This button (and the whole expanding functionality) should be a piece of `Card` component. But leave it like this for now. Lets do it as a separate task.

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +      <MarketsModal
This modal should be a piece of Card functionality and should not be inside Markets... Markets should only receive prop `:expanded-mode="true"` which would mean to display expanded version of markets. But the whole Modal open/close logic and Modal component should be on the upper level.

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +          :on-change="onSearch"
Communicating between components should be based on `$emit`s, you can actually use v-model and just `$emit` `input` inside the component:
https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +      default() {
`default: false` is enough

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +      border: 1px solid #7a7675;
For all colors please use tailwind config

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +      position: absolute;
Again absolute positioning is not needed for that (see comment about Modal functionality - it's gonna be part of the card, not markets widget). So should be moved there.

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/TheMarkets.vue
> +    .tickers-search {
This is not the good way to position element...
![image](https://user-images.githubusercontent.com/4411295/47478523-3c834380-d832-11e8-8dc7-d45944db7588.png)
It should be in a Card header slot

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        @click="changeSortField({ field: 'volUsd' })">Volume, USD</div>
currentTicker, not USD?

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +    <!--small-->
Can do another component for table header

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      >{{ priceTitle }}</div>
Merge latest dev into your branch and you'll have component for displaying table column title with sort arrows

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      default() {
default: false

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      this.sortField = (this.sortField[0] === '-') ? field : `-${field}`
What is this with `-`?

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +    font-weight: 600;
font-weights are in tailwind config too

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +    margin-top: 8px;
Please use rems

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        text-transform: none;
is it needed?

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      padding: 7px;
tailwind config or rem

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      padding: 7px;
tailwind config or rem

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +      transition: all 0.6s ease;
Specify which properties you transition on, please don't write transitions with `all`

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        .tickers-list__item {
Item styles should be in Item component

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      default() {
Should it be required?

2018-10-25 06:12 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      getVolumeFormat
Why put it into data? It is no some reactive properti nor it should be, you can directly access it without storing in data.

2018-10-25 06:12 UTC, roma219 commented on src/helpers/utils.js
> +export const getVolumeFormat = sum => sum.toString().replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g, '$1 ')
Please provide some in-code comments about how these functions work and what they do

2018-10-25 21:06 UTC, lapinlapin commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      default() {
why not?

2018-10-26 06:34 UTC, roma219 commented
@lapinlapin And please fill in the PR form:
![image](https://user-images.githubusercontent.com/4411295/47548640-496f6800-d902-11e8-82a5-23e310b7387c.png)

2018-10-26 06:45 UTC, roma219 commented
@lapinlapin 
1) re: sortings and `SortableHeaderItem` integration
Check out branch `80-account-prices-mode` (Portfolio component) for a convenient way to implement it usings `lodash/sortBy`

2) re: favourites & localstorage
No need to use localStorage in vue components - they are for data display, not this kind of logic. You can simply store a list of favourite asset's ids in market vuex module. And `vuex-persistedstate` will take care of caching this data (you'll only need to specify path to favourites on global store; see 'state/store.js')

2018-10-29 06:40 UTC, roma219 requested changes
1) Card component turning into Modal with scoped-slots
2) No component stuff like classes or templates in store
3) Split it into components more to make it more readable
4) Component should only have styles for itself, not for it's children
5) See comments

2018-10-29 06:40 UTC, roma219 commented on src/components/Card/Card.vue
> +        >
The Card component should not know anything about it's content (ex MarketsModal), it should turn into a modal at special icon click and send props `:expanded="true"` to slot via scoped slots, see https://vuejs.org/v2/guide/components-slots.html

2018-10-29 06:40 UTC, roma219 commented on src/components/Modal/Modal.vue
> +            <svgicon :name="'cancel'"/>
`name="cancel"`

2018-10-29 06:40 UTC, roma219 commented on src/components/Modal/Modal.vue
> +  top: -35px;
Was it a temporary decision to position it like that? It can be a a part of another block e.g. `modal-header`. We are gonna use this modal on mobile as well.

2018-10-29 06:40 UTC, roma219 commented on src/components/Modal/Modal.vue
> +  width: 800px;
Let's make it have full width while on a mobile device, see tailwind docs for it.

2018-10-29 06:40 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +      v-model.trim="searchValue"
Let's have it with `:value` prop instead and emiiting `input` event, so we can use `v-model` on this searchInput component

2018-10-29 06:40 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +      <svgicon :name="'cancel'"/>
name="cancel"

2018-10-29 06:40 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +      <svgicon :name="'search'"/>
name="search"

2018-10-29 06:40 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +    transform: scale(.7, .7);
Why transform it? it you want to change icon width/height you can do it via props https://github.com/MMF-FE/vue-svgicon

2018-10-29 06:40 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +    color: config('colors.white');
colors.text-primary

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +  favourites: {
Why Object? You can use array with ids?

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +        classes: ['tickers-list__field']
there should be no DOM classes info in store

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +const a = {
Please no this kind of names for variables, they should be self-explanatory... e.g. `types`

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +        title: 'Name/Vol, {currentTicker}',
This `{currentTicker}` should not be in store either... This is purely component's display logic

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        v-for="(field, index) in marketsField.small"
Computed? like `fields() { return this.expanded ? marketFields.large : marketFields.small }`

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        <SortableHeaderItem
it also has a title props that should be used for column title

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +        :class="[field.classes.concat({'_field-active': activeFieldIndex === index})]"
Looks way too complicated for what it does

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +  favourites: {
e.g.:
```
favourites: {
   'USD: ['POE', 'RPL']
   'BTC: ['BTS']
}
```

2018-10-29 06:40 UTC, roma219 commented on src/store/markets.js
> +        title: 'Name/Vol, {currentTicker}',
Actually any reason why you want to store this `marketFields` property in store? Seems it is never modified and not used by anything except the view component -> it should be inside vue component.

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +<template>
please split it into subcomponents by columns

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      default() {
? It should be required, right? So default is not needed

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      type: Function,
Don't send methods as props, use `$emit`

2018-10-29 06:40 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +    .tickers-list-row {
This styles are not for this component

2018-10-30 06:37 UTC, roma219 requested changes
Still needs changes, please looks throught file changed tab
![image](https://user-images.githubusercontent.com/4411295/47700286-03c6de00-dc27-11e8-822f-8f272350e765.png)
and fix every discussion, lot was missed previous times.

Also:
- Search bar is doing something
![image](https://user-images.githubusercontent.com/4411295/47700317-19d49e80-dc27-11e8-93c2-f49a2543b892.png)

- Sort arrows and not displayed correctly
![image](https://user-images.githubusercontent.com/4411295/47700341-2953e780-dc27-11e8-966c-fb5af75182df.png)
![image](https://user-images.githubusercontent.com/4411295/47700359-3a045d80-dc27-11e8-98a4-dd7445478858.png)
![image](https://user-images.githubusercontent.com/4411295/47700367-41c40200-dc27-11e8-8b09-363d04945ab1.png)

You might want to use new `SortableTable.vue` which will handle Header display and data sorting, so you'll only need to display items.

2018-10-30 06:37 UTC, roma219 commented on src/store/index.js
> +import markets from './markets'
put it into modules folder

2018-10-30 06:37 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItemPrices.vue
> +  .markets--expanded {
There should no be styles from some upper component here. You can get the expanded state from props.

2018-10-31 06:52 UTC, roma219 requested changes
![image](https://user-images.githubusercontent.com/4411295/47770889-325dbb00-dcf2-11e8-98f3-e1a6ae8973db.png) 
Needs to fix that.

Also check comments

And tweak a bit for the updated design (see zeplin):
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bd6f94bd929e70d2f0f4d23
![image](https://user-images.githubusercontent.com/4411295/47771022-ad26d600-dcf2-11e8-9b88-528ce07aec7d.png)

2018-10-31 06:52 UTC, roma219 commented on src/components/SortableHeaderItem/SortableHeaderItem.vue
> +    showIcon: {
showIcon = show Arrows or ? what is icon?

2018-10-31 06:52 UTC, roma219 commented on src/store/modules/markets.js
> +    BTCUSD: true,
Why would you need to store it a boolean variable, if they are all true? About ids see below

2018-10-31 06:52 UTC, roma219 commented on src/store/modules/markets.js
> +        id: 'USDZIL',
those ids are not gonna be like this, they are gonna be non-connected to bases e.g. 'USD' or '1.3.2'.

2018-10-31 06:52 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +          { title: 'Name/Vol, {currentTicker}', sortField: 'ticker', classes: ['tickers-list__field'] },
Was my fault, this is gonna be USD always, not currentTicker

2018-10-31 06:52 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +          { title: 'Name/Vol, {currentTicker}', sortField: 'ticker', classes: ['tickers-list__field'] },
And you should not send any classes/templates through props

2018-10-31 06:52 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +          { title: 'Name/Vol, {currentTicker}', sortField: 'ticker', classes: ['tickers-list__field'] },
It seems that rhey all have `tickers-list__field` class. For alignment, use props `align="left"`. Or you can actually hard code it inside Item component - you can also split it into smaller-subcomponent.

2018-10-31 06:52 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersList.vue
> +    .header-item__arrows {
These styles do not belong to this component

2018-10-31 06:52 UTC, roma219 commented on src/views/TheMarkets/MarketsTickersListItem.vue
> +      default() {
can be just `default: false`

2018-10-31 07:30 UTC, roma219 approved these changes

2018-10-31 07:31 UTC, merged