137 amount value shortener
bitshares/bitshares-community-ui pull request #138
Opened 2018-11-01 18:07 UTC by MindfulMe

#### What's this PR do?
Adds Amount Value Shortener function along with two unit tests (i.e. for millions and for thousands)
#### Where should the reviewer start?
The function is placed in helpers/utils.js, and named `amountValueShortener`
The unit tests can be found in the appropriate folder used for unit tests
#### How should this be manually tested?
In the browser check out Markets component on the appropriate page
or
`npm run test:unit`
#### Any background context you want to provide?
The value shortener can be improved even more in just several minutes to accept even bigger values (i.e. trillions and much much more)
#### What are the relevant tickets?
#137 
#### Screenshots (if appropriate)
<img width="74" alt="screen shot 2018-11-01 at 20 07 12" src="https://user-images.githubusercontent.com/26275425/47870239-c07c9300-de11-11e8-99ac-0dbe89baa63d.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
http://staging-ui.trusty.apasia.tech:8080/137-amount-value-shortener

#### Questions:
-

2018-11-01 18:09 UTC, MindfulMe commented
@roma219 I can quickly improve it to parse much bigger amounts to trillions and quadrillion ...

2018-11-01 18:19 UTC, roma219 requested changes
Needs some explanations

2018-11-01 18:19 UTC, roma219 commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
what does this regex mean?

2018-11-01 18:19 UTC, roma219 commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
what is $1 and how does this expression work?

2018-11-01 18:21 UTC, roma219 commented on tests/unit/amountValueShortener.spec.js
> +describe('amountValueShortener function', () => {
Also test with some less that 1k number

2018-11-01 18:29 UTC, MindfulMe commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
regular expression

2018-11-01 18:29 UTC, MindfulMe commented on tests/unit/amountValueShortener.spec.js
> +describe('amountValueShortener function', () => {
okay, will be done

2018-11-01 18:29 UTC, MindfulMe commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
I will also write a test for it

2018-11-01 18:30 UTC, MindfulMe commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
it matches digits

2018-11-01 18:36 UTC, MindfulMe commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
or did you mean the code explanation?

2018-11-01 18:37 UTC, MindfulMe commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
if so than it is used for substring match, here it is matches for the first substring

2018-11-01 18:40 UTC, roma219 requested changes
Needs explaining

2018-11-01 18:40 UTC, roma219 commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
what is  `'$1'` in this line of code?

2018-11-01 18:40 UTC, roma219 commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
I'am asking what exactly does it match? why there is `[0-9]` followed by `*[1-9]`?

2018-11-01 18:40 UTC, roma219 commented on src/helpers/utils.js
> +    { value: 1E3, symbol: 'k' },
what does 1E3 mean?

2018-11-01 18:40 UTC, roma219 commented on src/helpers/utils.js
> +  let data = [
why `data`? change it to something more clear

2018-11-01 18:42 UTC, MindfulMe commented on tests/unit/amountValueShortener.spec.js
> +    const amount = '100'
do you expect 0.1k or 100 as it is less than a thousand?

2018-11-01 18:48 UTC, MindfulMe commented on src/helpers/utils.js
> +  let data = [
okay, valuesToSymbols?

2018-11-01 18:49 UTC, MindfulMe commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
[0-9] is used to find all digit characters

2018-11-01 18:52 UTC, MindfulMe commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
`*[1-9]` matches 1-9 with more than 1 occurence before

2018-11-01 18:53 UTC, MindfulMe commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
selects the first substring removing every other substring that comes after

2018-11-01 18:53 UTC, MindfulMe commented on src/helpers/utils.js
> +    { value: 1E3, symbol: 'k' },
10^3

2018-11-01 18:54 UTC, MindfulMe commented on src/helpers/utils.js
> +    { value: 1E3, symbol: 'k' },
10 to the power of 3

2018-11-01 19:00 UTC, MindfulMe commented on src/helpers/utils.js
> +  return (amount / data[i].value).toFixed(1).replace(regex, '$1') + data[i].symbol
> what is `'$1'` in this line of code?

using it with .replace(regex, '$1') allows to trim unnecessary zeros like 199.10 to 199.1

2018-11-01 22:40 UTC, MindfulMe commented on src/helpers/utils.js
> +  let regex = /\.0+$|(\.[0-9]*[1-9])0+$/
man, it is a really simple regex

2018-11-02 18:35 UTC, MindfulMe commented on tests/unit/amountValueShortener.spec.js
> +    const amount = '100'
I leave it as 100 rather than 0.1, @roma219 if ok - merge, please

2018-11-03 13:04 UTC, merged