124 book tables
bitshares/bitshares-community-ui pull request #142
Opened 2018-11-03 09:14 UTC by lapinlapin

#### What's this PR do?
Created orderbook table
Add dynamic from mocks
Add logic of calculate volume and brush
#### Where should the reviewer start?
views/OrderBook/OrderBook.vue
#### How should this be manually tested?
http://localhost:8080/#/
#### Any background context you want to provide?
#### What are the relevant tickets?
#132 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/47950337-dd27e080-df61-11e8-821a-1e13f2fa5a76.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/124-book-tables
#### Questions:

2018-11-03 11:46 UTC, roma219 requested changes
Needs some tweaks. Will do a more thoughtful review later.

Next time please do it in an "one issue" = "one PR" fashion (re #132)

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBook.vue
> +      const maxFromBuy = orderBy(this.orderBook.buying, 'sum', 'desc')[0].sum
No need to order array to calculate max, just create method `getMaxOrderAmount` that recieves order array as an argument

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookLastPrice.vue
>        currentTicker: 'books/getCurrentTicker'
currentTicker is not used

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookLastPrice.vue
> +    width: 150px;//fixed for centred
px -> rem

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +      margin-right: 0.0325rem;
too much code repeat in these

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookLastPrice.vue
> +    background: config('colors.card-background');
why does it needs to have bg?

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookLastPrice.vue
>    <div class="order-book__price">
this is a separate entity, not a sub-block, pleace rename class to `order-book-price`

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTable.vue
> +      default() {
default: () => []

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTable.vue
> +    class="order-book__table"
`order-book-table`

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +    class="order-book__tableRow"
`order-book-table-row`

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +    class="order-book__tableRow"
Why there are two containers here, row and tableItem? Maybe it can be done with one?

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +          color: config('colors.button-text');
why `color.button-text`?

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to left, config('colors.buy') 100%, config('colors.card-background') 0%) !important;
gradient is not needed here, isn't it?

2018-11-03 11:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to right, config('colors.sell') 100%, config('colors.card-background') 0%) !important;
and here aswell

2018-11-03 11:47 UTC, roma219 commented
![image](https://user-images.githubusercontent.com/4411295/47951831-5bdb4880-df77-11e8-85dd-c237e950a950.png)

this should be aligned

2018-11-05 08:24 UTC, lapinlapin commented on src/views/OrderBook/OrderBook.vue
> +      const maxFromBuy = orderBy(this.orderBook.buying, 'sum', 'desc')[0].sum
moved maxum  to getters

2018-11-05 08:25 UTC, lapinlapin commented on src/views/OrderBook/OrderBookTableItem.vue
> +    class="order-book__tableRow"
no, maybe it will be better wrapped

2018-11-05 08:26 UTC, lapinlapin commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to right, config('colors.sell') 100%, config('colors.card-background') 0%) !important;
its a hover state, it is necessary

2018-11-05 17:44 UTC, roma219 requested changes
Needs a few changes (see comments)

2018-11-05 17:44 UTC, roma219 commented on src/store/modules/books.js
> +    const maxFromBuy = state.orderBook.buying.slice(0).pop().sum
these arrays are not gonna be sorted, so you need to calculate the max out of them here

2018-11-05 17:44 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to left, config('colors.buy') 100%, config('colors.card-background') 0%) !important;
@lapinlapin No need to use gradient when you can use simple background
`background-color: config('colors.buy')`

2018-11-05 17:44 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to right, config('colors.sell') 100%, config('colors.card-background') 0%) !important;
No need to use gradient when you can use simple background
background-color: config('colors.buy')

2018-11-05 17:44 UTC, roma219 commented on src/components/SortableHeaderItem/SortableHeaderItem.vue
> +        'header-item__title--sell': type === 'sell',
There are new props in `SortableTable` that you can use to achieve similar effect. `headerLeftPadding` and `headerRightPadding` - see how it was used in Markets and Account.

2018-11-05 17:52 UTC, roma219 commented
Also let's make right padding on the selling table a bit bigger it's not so close to border, use `1rem` 
![image](https://user-images.githubusercontent.com/4411295/48016473-ba055880-e13c-11e8-98e6-033452554bda.png)

2018-11-06 06:46 UTC, roma219 requested changes
A few more things + few things remain from previous reviews

2018-11-06 06:46 UTC, roma219 commented on src/store/modules/books.js
> +    const maxFromBuy = orderBy(state.orderBook.buying, 'sum', 'desc')[0].sum
Do you really need to order the whole array to know the maximum? This is overkill. Just create helper utility function that is gonna return max element, receiving array of objects and name of the field to compare:
`const maxBuyOrderSum = getMaxElement(state.orderBook.buying, 'sum')`

2018-11-06 06:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to right, config('colors.sell') 100%, config('colors.card-background') 0%) !important;
@lapinlapin

2018-11-06 06:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +            background: linear-gradient(to left, config('colors.buy') 100%, config('colors.card-background') 0%) !important;
@lapinlapin

2018-11-06 06:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +      :style="styleBackground"
Can't you apply this `styleBackground` to row element and get rid of this container?

2018-11-06 06:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +        'order-book-table-item--buy': type === 'buy',
why do you need these `--buy` and `--sell` suffixes both for row and item? You never have buy items inside sell rows, right?

2018-11-06 18:43 UTC, lapinlapin commented on src/views/OrderBook/OrderBookTableItem.vue
> +        'order-book-table-item--buy': type === 'buy',
cleaned

2018-11-06 18:44 UTC, lapinlapin commented on src/views/OrderBook/OrderBookTableItem.vue
> +      :style="styleBackground"
This is a compact property of computed, is it bad?

2018-11-06 18:46 UTC, roma219 commented on src/views/OrderBook/OrderBookTableItem.vue
> +      :style="styleBackground"
Form is fine, i just meant that you probably don't need both `item` and `row`

2018-11-06 18:51 UTC, roma219 requested changes
A bit of cleanup of useless props and it's good to go

2018-11-06 18:51 UTC, roma219 commented on src/components/SortableHeaderItem/SortableHeaderItem.vue
> +    type: {
This is not used anymore, remove please

2018-11-06 18:51 UTC, roma219 commented on src/components/SortableTable/SortableTable.vue
> +    type: {
This is not used anymore, remove please

2018-11-06 18:51 UTC, roma219 commented on src/helpers/utils.js
> +  return Math.max.apply(null, items.map(item => item[field]))
👍

2018-11-06 19:28 UTC, roma219 approved these changes

2018-11-07 17:54 UTC, merged