#145: add searchStr to store, move search go slot header
bitshares/bitshares-community-ui pull request #148
Opened 2018-11-05 14:47 UTC by lapinlapin

#### What's this PR do?
Add search to header slot
#### Where should the reviewer start?
Dashboard.vue
#### How should this be manually tested?
http://localhost:8080/#/
#### Any background context you want to provide?
#### What are the relevant tickets?
no tickets
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/48004698-c5e42100-e122-11e8-87f9-f1e7fafbe2bb.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/145-market-search
#### Questions:

2018-11-05 17:33 UTC, roma219 requested changes
All good. Only needs to encapsulate everything about search into separate `MarketsSearch` component (see comment).

2018-11-05 17:33 UTC, roma219 commented on src/views/Dashboard.vue
> +          <div
Let's move this whole block to separate `MarketsSearch` component. Or actually it seems that .search-wrapper and .tickers-search containers are not needed at all. So you can rename `SearchInput` to `MarketsSearch` and put all the vuex communications and methods into this separate component too. So in Dashboard it is gonna be just `<MarketsSearch slot="header"/>`

2018-11-05 19:11 UTC, lapinlapin commented on src/views/Dashboard.vue
> +          <div
fixed

2018-11-06 06:23 UTC, roma219 requested changes
Search Input shoud not be hidden when there is a search string active in it:
![image](https://user-images.githubusercontent.com/4411295/48046421-7c88e580-e1a5-11e8-9612-2bf689699577.png)
![image](https://user-images.githubusercontent.com/4411295/48046379-5400eb80-e1a5-11e8-8f23-42dc20c1114d.png)

2018-11-06 18:57 UTC, roma219 approved these changes
👍

2018-11-06 18:58 UTC, merged