146 orderbook scroll
bitshares/bitshares-community-ui pull request #149
Opened 2018-11-05 14:53 UTC by lapinlapin

#### What's this PR do?
Add scroll to buy/sell tables 
#### Where should the reviewer start?
views/OrderBook/OrderBookTable.vue
#### How should this be manually tested?
http://localhost:8080/#/
#### Any background context you want to provide?
#### What are the relevant tickets?
#124 
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/146-orderbook-scroll
#### Questions:

2018-11-05 17:49 UTC, roma219 requested changes
👍 
Just a few things:
1) see comment
2) Let's make a small padding at the bottom so there is no shadow visible when scrolled down fully.
![image](https://user-images.githubusercontent.com/4411295/48016258-3481a880-e13c-11e8-9307-bbedd0cdcbac.png)

2018-11-05 17:49 UTC, roma219 commented on src/views/Dashboard.vue
> +            :style="{'height': '100%'}">
Simply use OrderBook directly in slot:
`<OrderBook slot="body"/>`

2018-11-05 18:58 UTC, lapinlapin commented on src/views/Dashboard.vue
> +            :style="{'height': '100%'}">
fixed

2018-11-06 06:35 UTC, roma219 commented
@lapinlapin Sorry, it seems i wasn't clear enough... I didn't mean to remove shadows totally, in fact they were perfectly fine. I mean that there should be padding at the bottom (= height of the shadow) of the scrolling containers, so when scrolled fully down the shadow is not be visible. So that would kinda indicate that there is no more to scroll. 

And there are merge conflicts.

2018-11-07 17:55 UTC, roma219 commented
@lapinlapin please fix conflicts

2018-11-08 05:40 UTC, merged