91 Clear input button
bitshares/bitshares-community-ui pull request #158
Opened 2018-11-08 01:03 UTC by MindfulMe

#### What's this PR do?
Adds cross icon along with button functionality and function to clear the current input
#### Where should the reviewer start?
at Input.vue
#### How should this be manually tested?
Basically, you could just test it by typing in the input field in any of the pages
#### Any background context you want to provide?
The clear button appears only when some content is passed to the input. If the input contains an icon then the clear button will not show up as it is mostly unnecessary (i.e. places like copy/paste inputs)
#### What are the relevant tickets?
#91 
#### Screenshots (if appropriate)
<img width="1260" alt="screen shot 2018-11-08 at 02 58 36" src="https://user-images.githubusercontent.com/26275425/48171029-bde2d780-e302-11e8-9f05-a096b7cd519d.png">
<img width="1260" alt="screen shot 2018-11-08 at 02 58 09" src="https://user-images.githubusercontent.com/26275425/48171030-bde2d780-e302-11e8-9c22-269531565f45.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
http://staging-ui.trusty.apasia.tech:8080/91-clear-button
#### Questions:
No questions

2018-11-08 01:04 UTC, MindfulMe commented
@roma219 Review merge if ok

2018-11-08 05:47 UTC, roma219 requested changes
1) Doesn't work right - try focusing on other fields after
2) ![image](https://user-images.githubusercontent.com/4411295/48179959-99065880-e332-11e8-83ef-3fe0de1a06c1.png)
3) Doesn't look like design
![image](https://user-images.githubusercontent.com/4411295/48180051-f69aa500-e332-11e8-84c9-706ab1a6c6b2.png)

2018-11-08 05:47 UTC, roma219 commented on src/assets/svg/cross.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
Where is this icon from?

2018-11-08 05:47 UTC, roma219 commented on src/components/Input/Input.vue
> +      this.value = ''
Thats not the right way to change value

2018-11-10 15:05 UTC, MindfulMe commented on src/components/Input/Input.vue
> +      this.value = ''
@roma219 I have fixed the mutation of the `value` prop

2018-11-10 15:06 UTC, MindfulMe commented on src/assets/svg/cross.svg
> +<?xml version="1.0" encoding="iso-8859-1"?>
This is replaced now by the icon from as in zeplin

2018-11-11 18:15 UTC, roma219 requested changes
Needs a lot of changes. Please remove all you logic for handling clear button - all you need to do is `$emit` empty value and thats it.

2018-11-11 18:15 UTC, roma219 commented on src/components/Input/Input.vue
> +    class="input input--delete-icon">
why is this class?

2018-11-11 18:15 UTC, roma219 commented on src/components/Input/Input.vue
> +      if (this.clearInput) {
This is awfull.... please don't do it like this. You should not have and 'clearInput' variables

2018-11-11 18:15 UTC, roma219 commented on src/components/Input/Input.vue
> +      this.clearInput = false
what is this? It is not needed

2018-11-11 18:15 UTC, roma219 commented on src/components/Input/Input.vue
> +      if (this.clearInput) {
Do you understand that the way you do it you don't actually clear any data, but display empty?

2018-11-11 18:31 UTC, MindfulMe commented on src/components/Input/Input.vue
> +    class="input input--delete-icon">
got it

2018-11-11 18:31 UTC, MindfulMe commented on src/components/Input/Input.vue
> +      if (this.clearInput) {
got it

2018-11-11 18:31 UTC, MindfulMe commented on src/components/Input/Input.vue
> +      this.clearInput = false
got it

2018-11-11 18:57 UTC, MindfulMe commented
@roma219 review, merge if ok

2018-11-12 05:14 UTC, roma219 approved these changes

2018-11-12 05:15 UTC, merged