164 backup
bitshares/bitshares-community-ui pull request #168
Opened 2018-11-09 19:15 UTC by lapinlapin

#### What's this PR do?
Add 3 steps markup
Add navigate between them
#### Where should the reviewer start?
views/Backup/Backup.vue
#### How should this be manually tested?
http://localhost:8080/#/
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/48283216-e8e93a80-e46c-11e8-8a00-85780dd61520.png)
![image](https://user-images.githubusercontent.com/6066637/48283229-f30b3900-e46c-11e8-929b-9b166c364059.png)
![image](https://user-images.githubusercontent.com/6066637/48283241-fc94a100-e46c-11e8-8a2b-7142c16bcfe9.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/164-backup
#### Questions:

2018-11-11 18:23 UTC, roma219 requested changes
Ok, needs a few minor changes

2018-11-11 18:23 UTC, roma219 commented on src/views/Backup/Backup.vue
> +      @change="onChangeStep"
This is not a `change` event, isn't it? Better cal it `next` or something like this

2018-11-11 18:23 UTC, roma219 commented on src/views/Backup/BackupPhrase.vue
> +    <div class="backup-step-button">i’ve written it down</div>
For button please you the `Button` component - it has all the necessary styles

2018-11-11 18:23 UTC, roma219 commented on src/views/Backup/Backup.vue
> +      this.currentStep = step
You can just do `this.currentStep++` since you only switch to next step.

2018-11-13 21:56 UTC, lapinlapin commented on src/views/Backup/Backup.vue
> +      @change="onChangeStep"
steps can be backward and can be forward. Next does not fit

2018-11-13 21:57 UTC, lapinlapin commented on src/views/Backup/BackupPhrase.vue
> +    <div class="backup-step-button">i’ve written it down</div>
I made this in #170

2018-11-13 21:58 UTC, lapinlapin commented on src/views/Backup/Backup.vue
> +      this.currentStep = step
in my case, one value for both forward and backward. Do not need increment/decrement.

2018-11-15 15:30 UTC, roma219 approved these changes

2018-11-15 15:31 UTC, merged