collapsible card
bitshares/bitshares-community-ui pull request #172
Opened 2018-11-10 16:12 UTC by MindfulMe

#### What's this PR do?
Adds collapsible prop with appropriate behavior to the Card.vue component
#### Where should the reviewer start?
at Card.vue
#### How should this be manually tested?
On the components pages
#### Any background context you want to provide?
The prop collapses the card when enabled, also rotating the arrow button to -90deg
#### What are the relevant tickets?
#120 
#### Screenshots (if appropriate)
<img width="1046" alt="screen shot 2018-11-10 at 18 09 57" src="https://user-images.githubusercontent.com/26275425/48303551-16d58a00-e514-11e8-9516-def0a8c47f14.png">
<img width="147" alt="screen shot 2018-11-10 at 18 09 35" src="https://user-images.githubusercontent.com/26275425/48303553-176e2080-e514-11e8-9211-5f5d77902497.png">
<img width="1003" alt="screen shot 2018-11-10 at 18 09 21" src="https://user-images.githubusercontent.com/26275425/48303554-189f4d80-e514-11e8-843b-f04f71aa0fa1.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
http://staging-ui.trusty.apasia.tech:8080/120-collapsible-card
#### Questions:
-

2018-11-11 18:09 UTC, roma219 requested changes
Ok, but needs a few changes. Also reverse the arrow position opened-closed and arrow color (see zeplin)

2018-11-11 18:09 UTC, roma219 commented on src/components/Card/Card.vue
> +      <div
make it fade in and out with `<transition name="fade">`

2018-11-11 18:09 UTC, roma219 commented on src/components/Card/Card.vue
> +  height: 2.8rem;
Make the height change animated with css transition

2018-11-11 18:09 UTC, roma219 commented on src/components/Card/Card.vue
> +  transform: rotate(-90deg);
make this transform animated with css transition

2018-11-11 18:15 UTC, MindfulMe commented on src/components/Card/Card.vue
> +      <div
got it

2018-11-11 18:15 UTC, MindfulMe commented on src/components/Card/Card.vue
> +  height: 2.8rem;
got it

2018-11-11 18:15 UTC, MindfulMe commented on src/components/Card/Card.vue
> +  transform: rotate(-90deg);
got it

2018-11-11 18:24 UTC, roma219 commented
@MindfulMe And also me the arrow  style `cursor: pointer` please

2018-11-11 18:30 UTC, MindfulMe commented
@roma219 review, merge if ok

2018-11-12 05:22 UTC, roma219 approved these changes

2018-11-12 05:22 UTC, merged