196 active orders
bitshares/bitshares-community-ui pull request #209
Opened 2018-11-21 19:09 UTC by lapinlapin

#### What's this PR do?
Created folder for ActiveOrder
Added vuex
Added field of filled and logic of brush
etc
#### Where should the reviewer start?
views/OrderActive
#### How should this be manually tested?
https://localhost:8080/
#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/48863353-1d001c00-edda-11e8-8bce-c3c38d4bb181.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
#### Questions:

2018-11-22 11:07 UTC, lapinlapin commented
@roma219 
Added mocks / edited template
Added markup of remove (mini/expand)
Added action of remove / removing from table

2018-11-22 15:05 UTC, roma219 requested changes
Main points:
1) Rename `OrderActive` to `ActiveOrders` (and corresponding classes as well)
2) Create a separate component `TwoLineItem` to be used in all the tables
3) Small stuff (see comments)

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActive.vue
> +      tableHeadersActive: [
should be computed

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActive.vue
> +        return item.payAssetSymbol.toLowerCase().includes(search) ||
You don't need the part after `||` because empty string is included in every string

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActive.vue
> +    if (!this.expandMode) {
remove this mounted hook, won't be needed if you use computed for headers

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActive.vue
> +  .order-active {
and rename classes to `.active-orders`

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTable.vue
> +          :is-last="sortedItems.length - 1 === index"
Better use css `:last-child` in Item component

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTable.vue
> +      default() {
Whats the point of having default value as an empty array? It's better to have it `required: true` so it'll display warning in case it is not passed

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +      :class="{'order-active-table-row--expanded': expanded}"
Why this when you already have a parent node with `'order-active-table-item--expanded': expanded` ?

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +      return `rgb(${255 - R}, 255, 0)`
nice

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +    filled() {
No need for a computed to just add `%` in the end. Do it in template: `{{ filled }}%`

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +      if (this.expanded) {
`return this.expanded ? 18 : 10`

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderHistory/OrderHistoryTableItem.vue
> +    ._alignRight {
There is the same utility class in tailwind : `.text-right`, no need to create your own

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +    height: 3.9375rem;
Better make it `min-height` so that in case some text is transfered to the next line, it won't be cut

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +    color: config('colors.white');
`colors.primary`

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +      <div class="table-item">
Try it as a separate component named something like `TwoLineItem` with nest classes `.first-line` and `.second-line` (it is not base and ticker). This component could be used massively across several widgets.

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +    // align-self: center;
clean up comments

2018-11-22 15:05 UTC, roma219 commented on src/views/OrderHistory/OrderHistoryTableItem.vue
>      color: config('colors.white');
`colors.primary`

2018-11-22 15:11 UTC, roma219 commented
@lapinlapin 
Also font-family and font-sized are not the same as in zeplin:
https://app.zeplin.io/project/5ba4e8c9a61c41288762b16b/screen/5bedd330b557d829291159d2

And the wrong data displayed as `price`:
![image](https://user-images.githubusercontent.com/4411295/48910835-0d3c1280-ee82-11e8-8c44-980cd4bef0e0.png)

2018-11-22 15:17 UTC, roma219 commented
And the cross in expanded mode is too large
![image](https://user-images.githubusercontent.com/4411295/48911104-e6321080-ee82-11e8-9305-910f17362140.png)

2018-11-23 05:18 UTC, roma219 commented on src/views/OrderActive/OrderActiveTableItem.vue
> +      <div class="table-item">
Will be done separately - #212

2018-11-23 06:20 UTC, roma219 commented
@lapinlapin Still has unresolved discussions and font-sizes/letter-spacing are off a little bit

2018-11-23 06:48 UTC, lapinlapin commented
@roma219 take a look, please

2018-11-23 16:47 UTC, roma219 requested changes
Needs fixes of a few things:

1) Bottom row in table item should have font-size 14px, including fill percent (both tables)
![image](https://user-images.githubusercontent.com/4411295/48953277-578ec380-ef56-11e8-868c-86c186580169.png)
2) Letter spacings still missing in several places, please check all
![image](https://user-images.githubusercontent.com/4411295/48953722-d46e6d00-ef57-11e8-9968-38f6a49ba6bf.png)
3) Wrong filled number font size and position (should be aligned with top of of get, spend, etc) 
![image](https://user-images.githubusercontent.com/4411295/48953816-2616f780-ef58-11e8-867a-696380482358.png)

2018-11-24 07:26 UTC, lapinlapin commented
@roma219 fixed letter spacing/filled position
![image](https://user-images.githubusercontent.com/6066637/48965716-6798b880-efd3-11e8-86a8-4ec58cec5a92.png)

2018-11-24 12:03 UTC, roma219 approved these changes
👍

2018-11-24 12:03 UTC, merged