207 new order
bitshares/bitshares-community-ui pull request #215
Opened 2018-11-23 16:50 UTC by lapinlapin

#### What's this PR do?
-Created structure of NewOrder
-Created preliminary data format
-Added some components of this section
-Some of dynamic (change tabs, filled increased price)
-Generate title of button sell/buy
-Some modified Card (hide head, when not found prop of title)
#### Where should the reviewer start?
https://localhost:8080
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/48954054-fae0d800-ef58-11e8-90a6-977ebd89106f.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/207-new-order
#### Questions:

2018-11-23 18:17 UTC, roma219 requested changes
Lotsa stuff, see discussions

Also colors are off
![image](https://user-images.githubusercontent.com/4411295/48956511-60869180-ef64-11e8-8d33-e367a985e8ed.png)
![image](https://user-images.githubusercontent.com/4411295/48956517-67150900-ef64-11e8-8d53-da7cbede5d05.png)

2018-11-23 18:17 UTC, roma219 commented on src/components/Card/Card.vue
> +          :class="{'no-pt': !title}"
there is a tailwind class for that - `pt-0`

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +    operationTitle() {
please no html templating in computed values. use `computed`s to compute values, use them in templates afterwards. If you want to inject html into button, you need to modify component to accept optional slot instead of prop `title`.

2018-11-23 18:17 UTC, roma219 commented on src/store/modules/newOrder.js
> +  currentBase: 'BTC',
Remove the `tradeData` and `currentBase` and make state of the following format:
```
   base: 'BTC',
   quote: 'USD',
   marketSellPrice: 5610.02,
   marketBuyPrice: 5611.15,
   orderAmount: 0.02,
   type: 'buy'
```

Also use the default state function, which will be used later to reset state (see `orderBook` module for example)

2018-11-23 18:17 UTC, roma219 commented on src/store/modules/newOrder.js
> +const getters = {
`getBase`
`getQuote`
`getMarketSellPrice`
`getMarketBuyPrice`
`getOrderAmount`
`getOrderType`

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +    <NewOrderPrice
comment it out for now

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      :current-base="currentBase"
`:base`
`:quote`
`:sell-price`
`:buy-price`
`:active`
`@change="setOrderType"`

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +    .order-btn {
Do not change inner styles of the component from the outside. You don't need `position` and `width`, just use padding on parent container and display flex in parent container.  For colors - add types to `Button` component and set it through `props`. Also make sure the disabled state is displayed correctly.

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderPrice.vue
> +<template>
this component will be done as a separate issue

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      return `BUY ${this.currentBase}/USD`
use base and quote through props

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      <NewOrderTabsTitle
I don't think this component is needed, `:increased` is not needed, sell is always red, buy is always green, and they'll have different icons. Use icons from here : https://drive.google.com/drive/folders/1YnEJCUDbaK-DOS4Gj6pzWJSX0-anZ9DG

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +    activeTab: {
Why is it object? Can be just a string `buy`, `sell`

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      activeTab: {
should be received though getters from store

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +    activeTitle() {
remove as it as `activeTab` is gonna be a string

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +      :class="{'order-tabs-subtitle--increased': !!increased}"
this prop is not needed, buy is always green, red is always red (see prev comment)

2018-11-23 18:17 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +    margin-top: -0.4375rem;
Why these minus margins? Can't it be made via flex cleaner way

2018-11-26 18:29 UTC, lapinlapin commented on src/components/Card/Card.vue
> +          :class="{'no-pt': !title}"
pt-0 not apply(

2018-11-26 18:37 UTC, lapinlapin commented
@roma219 
![image](https://user-images.githubusercontent.com/6066637/49034460-18b17580-f1c3-11e8-9b1e-b9293811f8f6.png)
-Corrected your comments and also made changes to the layouts and new elements by design
-Work on graphic elements in another branch, do not worry)

2018-11-27 05:52 UTC, roma219 requested changes
Needs more changes.

Tips:
Focus more on separating components more as dumb/smart. `NewOrder.vue` should be a smart component, that handles all vuex data communication and all the child ones should be dumb, 
 presentational ones, that only `$emit` events to the smart component to signal of some user interaction.

2018-11-27 05:52 UTC, roma219 commented on src/components/Card/Card.vue
> +.collapse-btn {
why are you adding this? it is already nested inside .card

2018-11-27 05:52 UTC, roma219 commented on src/components/Card/Card.vue
> +.collapse-btn--active {
why are you adding this? it is already nested inside .card-header

2018-11-27 05:52 UTC, roma219 commented on src/store/modules/newOrder.js
> +  activeTab: 'buy',
activeTab = type, `type` should be used instead of `activeTab` in the module & vue component

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      :class="{
It shouldn't be a class, but a `:type` prop (there are already `primary` and `secondary` types in `Button` component), which should consisnt background, hover and disabled styles.

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +    .order-btn {
Wasn't resolved. You shouldn't change position of the component from the parent component. Instead make adjustments to parent component - display flex, paddings etc.

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderPercents.vue
> +<template>
Can you please remove this file from PR as it is not in this issue and use it in the issue for this component, so that next PR could be done easier.

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderPrice.vue
> +<template>
Can you please remove this file from PR as it is not in this issue and use it in the issue for this component, so that next PR could be done easier.

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      quote: 'newOrder/getQuote'
should be received as props as well

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +  data() {
empty data is not needed

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +    ._buy {
are these classes needed? you already have `--sell` and `--buy`

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      setActiveTab: 'newOrder/setActiveTab'
You should focus of separating dumb and smart components more... `setActiveTab` should just `$emit` event `change` with new tab name, so that the parent (smart) component could set the right order type in vuex.

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmF
Use `vue-svgicon` instead

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +        &:after {
why is this needed?

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      :sell-price="marketSellPrice"
should have a `@change` to change type

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +import Btn from '@/components/Button/Button'
There is an `index.js` file there - you can import it like `import Button from '@/components/Button`

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +  data() {
No need for an empty data

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +        return `${this.marketBuyPrice} ${this.base}`
Should use an `orderAmount` instead of `marketBuyPrice` for both buy and sell

2018-11-27 05:52 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +        &:before {
Doesn't seems like any `:before:` or `:after` elements are needed here. Use `vue-svgicon` component for icons instead.

2018-11-27 12:30 UTC, lapinlapin commented on src/components/Card/Card.vue
> +.collapse-btn--active {
and that

2018-11-27 12:31 UTC, lapinlapin commented on src/views/NewOrder/NewOrderPercents.vue
> +<template>
deleted

2018-11-27 12:34 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabs.vue
> +    ._buy {
this class is need. _but _sell - default classes and they contain colors of .5, but --sell --buy is active tab state. Also i added to inner _but/_sell svgicon for structure

2018-11-27 12:34 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +        background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz48IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmF
replaced

2018-11-27 12:35 UTC, lapinlapin commented on src/views/NewOrder/NewOrder.vue
> +      :sell-price="marketSellPrice"
dont understand this.... i added for type prop action, and what need for sell-price prop?

2018-11-27 12:38 UTC, lapinlapin commented on src/views/NewOrder/NewOrder.vue
> +import Btn from '@/components/Button/Button'
Button its a native DOM  element, but when i import and use Button i have an error by conflict. Just because i used Btn. Similarly problem i saw with Input

2018-11-27 12:39 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +        &:after {
removed

2018-11-28 12:12 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      :sell-price="marketSellPrice"
all good

2018-11-28 12:26 UTC, roma219 requested changes
Needs styling fixes. You should stop using absolute positioning - 90% of the time it is not needed. Use flexbox instead.

Change positioning in in new order container. Just use flex display and align items accordingly in the main new order container.

Also improve elements inside tabs positioning.

+ few minor stuff

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +        return `${this.orderAmount} ${this.base}`
this condition is useless? always returns the same

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +    buyTitle() {
these computeds can be combined : buy/sell is your `type` variable

2018-11-28 12:26 UTC, roma219 commented on src/components/Button/Button.vue
> +  position: absolute;
why there is positioning in button type? type is only for styling

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +          .order-tabs-subtitle {
stop assigning styles to elements from another components

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +        position: absolute;
not needed

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +        position: absolute;
not needed

2018-11-28 12:26 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      height: 3.5625rem;
better 100%

2018-11-28 12:30 UTC, roma219 commented
@lapinlapin https://css-tricks.com/snippets/css/a-guide-to-flexbox/

2018-11-28 18:10 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabs.vue
> +    buyTitle() {
I am added method. Computed will not work here, because here two static tab elements but computed one

2018-11-28 18:10 UTC, lapinlapin commented on src/components/Button/Button.vue
> +  position: absolute;
removed

2018-11-28 18:10 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabs.vue
> +          .order-tabs-subtitle {
ok

2018-11-28 18:10 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabs.vue
> +        position: absolute;
moved icons to inner component

2018-11-29 06:03 UTC, roma219 requested changes
just a few things left and

![image](https://user-images.githubusercontent.com/4411295/49202381-7c02f980-f3b5-11e8-8858-a969ae7b2390.png)
titles should be aligned - can be achieved by having margin-top or transparent border in inactive state

2018-11-29 06:03 UTC, roma219 commented on src/components/Button/Button.vue
> +  }
there should also be a `--disabled` style for both buy and sell buttons

2018-11-29 06:03 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +      margin-top: auto;
what if we add another button on top? we'll need to specify these ugly `margin: 2%`s again? And what if the card becomes wider - that margins are gonna be different. And thats not the best way to set width.
Solution: Wrap `Btn` with container, that is gonna have padding. These container will contain other widget's elements in future.

2018-11-29 06:03 UTC, roma219 commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +    inActive: {
should be `isActive`?

2018-11-29 06:03 UTC, roma219 commented on src/views/NewOrder/NewOrderTabs.vue
> +      color: rgba(121, 198, 15, .5);
move this color to tailwind config - you also use it `NewOrderTabsTitle.vue`

2018-11-29 18:15 UTC, lapinlapin commented on src/components/Button/Button.vue
> +  }
added this state to button for each type (buy/sell), but dont created logic for that work. For test i added classes

2018-11-29 18:16 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabs.vue
> +      color: rgba(121, 198, 15, .5);
added disabled colors to lib

2018-11-29 18:16 UTC, lapinlapin commented on src/views/NewOrder/NewOrderTabsTitle.vue
> +    inActive: {
no, it's enough

2018-11-29 18:58 UTC, roma219 requested changes
Just one more thing

2018-11-29 18:58 UTC, roma219 commented on src/components/Button/Button.vue
> +      'btn--buy-disabled': type === 'buy-disabled',
No.
Examine the `Button` component. It has `disabled` property. When the `type` prop is buy/sell and `disabled` is true -> add background-color styles. Can be done with css only (there is already a disabled class).

2018-11-29 19:22 UTC, roma219 commented
@lapinlapin 
Still not aligned
![image](https://user-images.githubusercontent.com/4411295/49246145-3da52300-f425-11e8-8fc4-262e527e170b.png)

2018-11-29 20:42 UTC, lapinlapin commented
@roma219 vertical align in tabs must be ok. i made this in prior commits. Maybe cache?

2018-11-30 05:18 UTC, roma219 approved these changes

2018-11-30 05:18 UTC, merged