Branch 225 update markets
bitshares/bitshares-community-ui pull request #226
Opened 2018-11-29 19:01 UTC by lapinlapin

What's this PR do?
Updated markets mini/expand version

Where should the reviewer start?
How should this be manually tested?
https://localhost:8080/

Any background context you want to provide?
What are the relevant tickets?
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-225-update-markets
#### Questions:

2018-11-29 19:04 UTC, roma219 commented
@lapinlapin 
You are just pasting the wrong url, check the http://staging-ui.trusty.apasia.tech:8080/
the correct one is - http://staging-ui.trusty.apasia.tech:8080/branch-branch-225-update-markets/

2018-11-29 19:07 UTC, roma219 commented
1)
![image](https://user-images.githubusercontent.com/4411295/49245272-e736e500-f422-11e8-9e68-2e92388c440a.png)
First two column items shouldn't be centrally aligned

2) Missing the $
![image](https://user-images.githubusercontent.com/4411295/49245309-fae24b80-f422-11e8-86f7-a737aed86548.png)

3) Correct `getFloatCurrency` function to return `0` instead of empty string when parsing zero
![image](https://user-images.githubusercontent.com/4411295/49245350-1e0cfb00-f423-11e8-9d9b-7267d2b6812a.png)

2018-11-29 19:15 UTC, roma219 requested changes
Overall ok, but needs changes

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
> +      return getFloatCurrency(this.item.price).toString()
getFloatCurrenct already return string, no need for `toString`

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
> +      return `/${this.item.base}`
Do this in template/via slot

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
> +      return (getFloatCurrency(this.item.usdPrice) || 0).toString()
no need for getFloatCurrency. We use different way to parse trim dollar prices and it is already done at this point

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
> +    align-items: center;
not needed

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
>        <div class="tickers-list__item _alignRight">
also please remove `_alignRight` classes in favour of tailwindcss ones

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
>          ._increase {
what are these classes? Why there is a different font size for drop and increase?

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
> +        ._tickerTitle {
is this class used/needed at all?

2018-11-29 19:15 UTC, roma219 commented on src/views/Markets/MarketsListItemPrices.vue
>          .tickers-list__itemVolume {
is this class used/needed at all?

2018-11-29 20:18 UTC, lapinlapin commented on src/views/Markets/MarketsListItemPrices.vue
>          ._increase {
its need. this classes set font size in expand mode, because that size must be 25px, but in tailwind not found this size

2018-11-29 20:18 UTC, lapinlapin commented on src/views/Markets/MarketsListItemPrices.vue
>          .tickers-list__itemVolume {
yes, this class use in expand first field

2018-11-29 20:19 UTC, lapinlapin commented on src/views/Markets/MarketsListItemPrices.vue
> +        ._tickerTitle {
for mini version i removed this class

2018-11-29 20:21 UTC, lapinlapin commented on src/views/Markets/MarketsListItemPrices.vue
> +    align-items: center;
i added prop to twoLineItem for removed top padding. Padding used in active/history, but here it is not necessary. align-items removed too, and to last two field added padding top

2018-12-01 09:21 UTC, roma219 approved these changes

2018-12-01 09:22 UTC, merged