(#201) Desktop Header
bitshares/bitshares-community-ui pull request #230
Opened 2018-12-01 17:05 UTC by Keegan-lee

#### What's this PR do?
- Aligns Header items
- Adds Deposit and Withdraw buttons
- Conforms Header Items style to Zeplin designs

#### Where should the reviewer start?
Header.vue
HeaderUserInfo.vue

#### How should this be manually tested?
- Compare the working vue to the designs laid out on Zeplin

#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
#### Questions:

2018-12-02 20:20 UTC, roma219 requested changes
Needs to match the design:
![image](https://user-images.githubusercontent.com/4411295/49344424-0c785d00-f688-11e8-83d0-0fa39c691e64.png)

1) Change Bitshares Logo size
2) Header should have a background color, paddings & margin
3) Use existing `Button` component + modify it to match the design
4) Modify user name styling to match design (font size, weight, color)
5) Fix merge conflicts

2018-12-02 20:20 UTC, roma219 commented on src/views/Header/Header.vue
> +      <Button
Please use an existing `Button` component (`src/components/Button`) with type=`secondary` and size=`small`. If the size of the button is incorrect in this case, modify `Button` component `btn--small` styles.

2018-12-02 20:20 UTC, roma219 commented on src/views/Header/HeaderUserInfo.vue
> +    padding-right: 10px;
Please use `rem` instead of `px`

2018-12-03 14:35 UTC, Keegan-lee commented on src/views/Header/Header.vue
> +      <Button
Thanks for the suggestions. I've made the changes. Looks much better now, I see in Zeplin where I need to pay attention to the styles. This should help.

2018-12-03 14:35 UTC, Keegan-lee commented on src/views/Header/HeaderUserInfo.vue
> +    padding-right: 10px;
Done.

2018-12-04 06:30 UTC, roma219 requested changes
- > Header should have a background color, paddings & margin

Still no bg
![image](https://user-images.githubusercontent.com/4411295/49422317-7f76f600-f7a4-11e8-9a5f-5f14ede0dd8e.png)

- Needs to use Button component (`src/components/Button`)
- Please name branches like `123-desktop-header` (without `(`)

2018-12-04 06:30 UTC, roma219 commented on src/views/Header/Header.vue
> +      <Button
We have an existing UI components stored in `src/components`, please use `Button` component from there. Examine it & it's props and modify `small` appearance of the button to fit design.

2018-12-04 06:30 UTC, roma219 commented on src/views/Header/Header.vue
> +  background-color: var(--black);
it should be black with opacity 0.2

2018-12-04 06:30 UTC, roma219 commented on src/views/Header/Header.vue
> +  width: 1280px;
No need to set width hard like that - it results in this on smaller screens:
![image](https://user-images.githubusercontent.com/4411295/49423013-fa411080-f7a6-11e8-8187-4b792497f650.png)

2018-12-05 04:17 UTC, Keegan-lee commented on src/views/Header/Header.vue
> +  width: 1280px;
I found a way around this. This was tough, because of the header being black with opacity of .2. 

The contents of the header would have taken on the opacity (no way around this) of the background. 

So I set a backdrop to the background, and made that black with opacity .2. I made this the full width. Set position: absolute, and made it always stick to right: 0.

Take a look at the code. It looks good now.

2018-12-05 15:19 UTC, roma219 commented on src/views/Header/Header.vue
> +  width: 1280px;
> I found a way around this. This was tough, because of the header being black with opacity of .2. The contents of the header would have taken on the opacity (no way around this) of the background.

You can achieve it by setting background color to color of rgba format, e.g.:
```
background-color: rgba(0, 0, 0, 0.2)
```

2018-12-05 15:49 UTC, roma219 requested changes
Better, but needs a bit of improvements

2018-12-05 15:49 UTC, roma219 commented on src/views/Header/Header.vue
> +.header-btn {
Please replace this button styles with passing a prop `size="small"` to `Button`. After that, if is needed, modify `Button` component to have appropriate style when prop `size="small"` is passed.

2018-12-05 15:49 UTC, roma219 commented on src/views/Header/HeaderUserInfo.vue
> +    font-size: 15px;
We use `rem`s instead of `pixels`

2018-12-05 15:49 UTC, roma219 commented on src/views/Header/Header.vue
> +        class="header-btn lg:w-1/3"
Why does it have `lg:w-1/3` style?

2018-12-05 15:49 UTC, roma219 commented on src/views/Header/Header.vue
> +    <div class="lg:w-1/3">
These `<div class="lg:w-1/3">` are not needed here - they are gonna be displayed just fine as they are because of `display: flex` on `.header` container

2018-12-05 20:06 UTC, Keegan-lee commented on src/views/Header/Header.vue
> +    <div class="lg:w-1/3">
This class keeps the deposit/withdraw buttons centred on the page, the logo on the right, etc. The items will abide by the flex rules, but wont be consistently in place as shown on the designs.

2018-12-09 18:22 UTC, roma219 commented on src/views/Header/Header.vue
> +.header-btn {
Was not resolved. You should modify Buttons sizes through classes, but instead modify `small` styles inside `Button` component

2018-12-09 18:24 UTC, roma219 commented on src/views/Header/HeaderUserInfo.vue
> +    font-size: 15px;
Not resolved.

Change all occurances of `px` to `rem`s. 1rem = 16px.
https://medium.com/@julienetienne/pixels-are-dead-faa87cd8c8b9

2018-12-09 18:25 UTC, roma219 commented on src/views/Header/Header.vue
> +.header-btn {
@Keegan-lee

2018-12-09 18:25 UTC, roma219 commented on src/views/Header/HeaderUserInfo.vue
> +    font-size: 15px;
@Keegan-lee

2018-12-09 18:26 UTC, roma219 requested changes
See prev discussions - some is not resolved.

2018-12-09 18:26 UTC, roma219 commented on src/views/Header/Header.vue
> +.inline-block {
No need for a separate class for that

2018-12-09 22:09 UTC, roma219 approved these changes

2018-12-09 22:09 UTC, merged