Neworder input
bitshares/bitshares-community-ui pull request #245
Opened 2018-12-03 19:41 UTC by lapinlapin

#### What's this PR do?
Added blocks of input
#### Where should the reviewer start?
views/newOrder/NewOrderInput
#### How should this be manually tested?
https://localhost:8080/
#### Any background context you want to provide?
#### What are the relevant tickets?
#237 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/49397413-8bcf6480-f74c-11e8-943f-8c6a581063c4.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-neworder-input
#### Questions:

2018-12-03 19:43 UTC, lapinlapin commented
@roma219 I didn’t use simple input, it doesn’t fit the design much, did customization instead

2018-12-04 05:56 UTC, roma219 requested changes
- Misses issue number
![image](https://user-images.githubusercontent.com/4411295/49421771-58b7c000-f7a2-11e8-9d6f-9229a305eaa8.png)
- All PRs should be branched out and target `dev` branch
- Needs some changes - see comments

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> +      'input--value': valueMode
input--value-mode

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> +    note: {
what is this?

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> +      if (this.valueMode && !this.value) {
why are you emitting placeholder?

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> +  text-align: center;
change text-align to a separate prop - `:centered="true"`. It's gonna be needed later without value-mode.

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> -  text-transform: uppercase;
why?

2018-12-04 05:56 UTC, roma219 commented on src/components/SimpleInput/SimpleInput.vue
> +    text-align: center;
why 2 text-aligns?

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +    aside: {
Again - no component should position itself like that. This component is gonna be used in a lot of situations without need to have magin-left: 1rem. Please remove and position these component by their container in NewOrder.vue.

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +      value: this.placeholder
what is this?

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +      value: this.placeholder
remove

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +    margin-top: -0.875rem;
remove - see positioning comment

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +    <div class="new-order-input--title">{{ title }}</div>
it is not a modifier (`--title`)

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +    <div class="new-order-input--note">{{ note }}</div>
it is not a modifier (`--note`)

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +      :note="note"
what is note?

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderInput.vue
> +    &--field {
not used

2018-12-04 05:56 UTC, roma219 commented on src/views/NewOrder/NewOrderPercentSelectorItem.vue
> +<template>
what is this? This issue has nothing to do with percent selector. And for PercentSelector - separate item component is not needed.

2018-12-05 06:54 UTC, roma219 approved these changes

2018-12-05 06:55 UTC, roma219 commented
@lapinlapin there are merge conflicts

2018-12-05 06:58 UTC, lapinlapin commented
@roma219

2018-12-05 07:03 UTC, merged