248 backup imp
bitshares/bitshares-community-ui pull request #255
Opened 2018-12-06 17:59 UTC by lapinlapin

#### What's this PR do?
-Made new forms
-Added logic for change forms
-Some refactoring of stepConfig
-Some mini fixes
-Editing unlock form
#### Where should the reviewer start?
views/Backup/BackupMenu
views/Backup/BackupKeyDownload
#### How should this be manually tested?
https://localhost:8080
#### Any background context you want to provide?
#### What are the relevant tickets?
#248 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/49602531-c11cc200-f999-11e8-91b7-d1b47d39edf1.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-248-backup-imp
#### Questions:

2018-12-09 18:20 UTC, roma219 requested changes
Modal component has been improved for better display (100% width and height on mobile) and now Backup needs massive layout remakes:

1) See `@/views/Deposit/DepositWidget` for example of how such modals should be composed. Width can wary (especially on mobile) so there should not be any hard-coded width or stuff like `width: 80%`
2) Make it adjust to 100% on mobile correctly (see Deposit for example)
3) Remove media-queries
4) cleanup css from unnecessary stuff (`height: auto` etc)

2018-12-11 20:58 UTC, lapinlapin commented
@roma219 updated

2018-12-11 21:05 UTC, roma219 approved these changes
👍

2018-12-11 21:05 UTC, roma219 commented on src/store/modules/backup.js
> +  showBackupModal: true
revert

2018-12-11 21:05 UTC, roma219 commented on src/views/Backup/Backup.vue
> +    <!--<div
remove commented

2018-12-11 21:19 UTC, lapinlapin commented on src/store/modules/backup.js
> +  showBackupModal: true
done

2018-12-11 21:22 UTC, roma219 approved these changes

2018-12-11 21:23 UTC, merged