256 floatcurrency
bitshares/bitshares-community-ui pull request #258
Opened 2018-12-07 19:46 UTC by lapinlapin

#### What's this PR do?
Fixed method
Add test case
**getFloatCurrency(191827.41133)** _// 191827.41_
**getFloatCurrency(50)** _// 50_
#### Where should the reviewer start?
/helpers/utils/getFloatCurrency
#### How should this be manually tested?
https://localhost:8080
#### Any background context you want to provide?
#### What are the relevant tickets?
#256 
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-256-floatcurrency
#### Questions:

2018-12-09 18:14 UTC, roma219 requested changes
Add a test case for
> input: 191827.41133 output: .1918274

2018-12-09 18:14 UTC, roma219 commented on src/helpers/utils.js
> +  const value = hasPoint() ? n.toString().replace(/0+$/, '') : n.toString()
No need to convert it to string 3 times

2018-12-10 06:24 UTC, lapinlapin commented on src/helpers/utils.js
> +  const value = hasPoint() ? n.toString().replace(/0+$/, '') : n.toString()
fixed

2018-12-10 06:25 UTC, lapinlapin commented
> Add a test case for input: 191827.41133 output: .1918274

Its incorrect case. Must begin with a point when the first number is 0

2018-12-10 07:37 UTC, roma219 approved these changes

2018-12-10 07:37 UTC, merged