Button
bitshares/bitshares-community-ui pull request #27
Opened 2018-09-22 07:50 UTC by MindfulMe

#### What's this PR do?
This pr modifies the button component
#### Where should the reviewer start?
From Button.vue and related files) including doc and tests
#### How should this be manually tested?
Checking out the button component on localhost:8080
#### Any background context you want to provide?
Nope
#### What are the relevant tickets?
[Button component](https://github.com/bitshares/bitshares-community-ui/issues/12)
#### Screenshots (if appropriate)
#### Questions: 
What could be corrected?

2018-09-22 08:13 UTC, roma219 requested changes
Ok for the first PR, but needs more work

2018-09-22 08:13 UTC, roma219 commented on package.json
> +    "vue-button-spinner": "^2.2.0",
There is no need for the lib. Just make a copy of this component - https://raw.githubusercontent.com/TrustyFund/trusty-ui-vue/master/client/components/UI/Spinner.vue, and place it into `src/components/Spinner` directory (same as button) and import it into Button.vue

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.md
> +[ref](https://www.npmjs.com/package/vue-button-spinner)
see above

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.vue
> +  data () {
You don't need data in this component at all - everything is recieved throught props

2018-09-22 08:13 UTC, roma219 commented on tests/unit/button.spec.js
> +  it('renders props.text when passed', () => {
Rightly done. But also need to test every prop like that and click event.

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.md
> +
Here, after you've completed the component, should be different examples of the button - like button with different props passed to it.

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.vue
> +    :isLoading="isLoading"
This does nothing. What we want to do, is style the button and modify it's behaviour based on a props passed to it. You can do it throught [class and style bindings ](https://vuejs.org/v2/guide/class-and-style.html#Object-Syntax).
So for the case of loading it should be like that: `<button :class="{'btn--loading': loading}">` which will asign the class `btn--loading` to button when the prop `loading` is true.  And in `<styles>` section you define class `.btn-loading` and add css rules into it - in this case default cursor and pointer-events: none (to prevent user from clicking it). User tailwindcss classes for it.

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.vue
> +    :disabled="isDisabled"
Do it class-binding way as well. Add class 'btn--disabled' when prop disabled is true. Disabled button should have slight opacity, default cursor and no 'click' event emitted on click.

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.vue
> +import VueButtonSpinner from 'vue-button-spinner'
Import component i linked above here (Spinner.vue)

2018-09-22 08:13 UTC, roma219 commented on src/components/Button/Button.vue
> +    size: {
Size prop should be handled by classes (like loading and disabled) 'btn--smal: size === 'small'

2018-09-22 11:57 UTC, MindfulMe commented
ok, hopefully now nothing is missed

2018-09-22 18:59 UTC, roma219 requested changes
Needs more changes and passing tests

For tests:
- check out https://vue-test-utils.vuejs.org/ docs for writing unit-tests for vue components
- test cases: besides text prop (which is done) : 'click' event emitted when clicking the button; 'click' event not emitted when clicking the button that is disabled or loading.
- And actually run the tests with command `npm run test:unit` to make sure all tests are passing

Button also should have 'cursor: pointer'

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +  <button @click="$emit('click')" class="btn btn-blue" :class="{'btn--disabled': disabled, 'btn--small':size === 'small', 'btn--big': size === 'big'}"
If you have more than 2 attributes/props please write'em as a column like that:
```
<button
    class="btn"
   :class="..."
   @click=..."
>
  {{ text }}
</button>
```

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +  <button @click="$emit('click')" class="btn btn-blue" :class="{'btn--disabled': disabled, 'btn--small':size === 'small', 'btn--big': size === 'big'}"
Needs a 'btn--loading' class as well to make it non-clickable (pointer-events: none)

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +    :isLoading=loading
Not used

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +    width: {
The default should be `standard` that displays it as now, and 'full' should make it 100% wide

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +    callback: {
No need for this prop

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +  cursor: not-allowed;
Please use tailwindcss classes (https://tailwindcss.com/docs/pointer-events/#app) instead 
e.g.
`@apply pointer-events-none opacity-50`;

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Loader.vue
> +<template>
Move it to a separate component folder in components: `src/components/Spinner/Spinner.vue`. No need for tests for it, just add three examples (sized) in styleguidist in Spinner.md

2018-09-22 18:59 UTC, roma219 commented on tests/unit/button.spec.js
> +    expect(wrapper.text()).toMatch(loading)
Why are you expecting wrapper.text() to match 'false'? Tests fail

2018-09-22 18:59 UTC, roma219 commented on tests/unit/button.spec.js
> +  it('renders props.isDisabled when passed', () => {
it('<test-name>') should describe the test case you are testing against, Button.vue doesn't have `isDisabled` prop and it shouldn't render it.

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +      default: 'Button'
default should be empty string

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +    /** Sets loading state
prop `type` doesn't set loading state. Make it add 'btn--round' class that adds a large `border-radius` to a button, so it looks round when no text passed. We will use it to have small icon buttons.

2018-09-22 18:59 UTC, roma219 commented on src/components/Button/Button.vue
> +  methods: {
No need for `methods` parameter that has no methods

2018-09-24 05:51 UTC, dls-cipher commented
@roma219 - review requested changes and let me know when this can be merged. Thanks

2018-09-24 06:04 UTC, roma219 commented
@dls-cipher It has work in progress ("wip:")

@MindfulMe Remove the "wip:" prefix when you are done and assign to me

2018-09-24 10:28 UTC, roma219 commented
@MindfulMe MR conflict, please fix

2018-09-24 10:36 UTC, roma219 requested changes
@MindfulMe Please read through this guides to get an idea of what is unit-testing .vue components is about:
https://vue-test-utils.vuejs.org/guides/getting-started.html
https://vue-test-utils.vuejs.org/guides/#common-tips

See https://vue-test-utils.vuejs.org/api/wrapper/#properties for wrapper properties and methods.

2018-09-24 10:36 UTC, roma219 commented on src/components/Button/Button.vue
> +  :class="{'btn--loading': loading, 'btn--disabled': disabled, 'btn--small':size === 'small', 'btn--big': size === 'big', 'btn--wide': width === 'full', 'btn--round':type==='round'}"
transfer this to newlines too

2018-09-24 10:36 UTC, roma219 commented on tests/unit/button.spec.js
> +    expect(wrapper.text()).toMatch(disabled)
Disabled is a boolean, and not a text that renders inside button, you are testing it wrong. Test whether or not `disabled = true` and clicking the buttons emits `('click')` event

2018-09-24 10:36 UTC, roma219 commented on tests/unit/button.spec.js
> +    expect(wrapper.text()).toMatch(loading)
This is not a test to test loading state, wrapper.text() should not match "loading" as it s Boolean

2018-09-24 10:36 UTC, roma219 commented on package.json
> +    "vuex-bitshares": "^0.2.4"
Why is that? Revert change please

2018-09-24 10:36 UTC, roma219 commented on src/components/Button/Button.vue
> +  :class="{'btn--loading': loading, 'btn--disabled': disabled, 'btn--small':size === 'small', 'btn--big': size === 'big', 'btn--wide': width === 'full', 'btn--round':type==='round'}"
Write it as a column as well

2018-09-24 10:36 UTC, roma219 commented on tests/unit/button.spec.js
> +  it('renders props.isDisabled when passed', () => {
not fixed

2018-09-24 12:45 UTC, roma219 requested changes
@MindfulMe Good, just a few more tests tweaks and it is done.

And pull staging and merge it into your branch to fix merge conflics please.

2018-09-24 12:45 UTC, roma219 commented on tests/unit/button.spec.js
> +describe('Button.vue', () => {
Please move all tests in one suite (everything into 1 describe func) and name each according to what it does, like that:
```
describe('Button.vue', () => {
   it('renders props.text when passed', () => { ... })
   it('is disabled when props.disabled is passed', () => { ... })
   it('emits event.click when clicked, () => { ... })
}
```

2018-09-24 12:45 UTC, roma219 commented on tests/unit/button.spec.js
> +    expect(wrapper.props('disabled')).toBe(true)
No need to test for a prop value you just passed...
Instead better check that inner button has `disabled` attribute

2018-09-24 17:32 UTC, roma219 approved these changes
Approving, but please read more on the topic of unit-testing vue components (see links provided earlier). I'll write some example tests soon, which you'll be able to refer in future.

2018-09-24 17:33 UTC, roma219 commented
@dls-cipher @hisinbox merge please

2018-09-25 05:38 UTC, merged