integrate backup file
bitshares/bitshares-community-ui pull request #282
Opened 2018-12-13 21:19 UTC by ololokiras

#### What's this PR do?
generate backup .bin fle
#### Where should the reviewer start?
src/views/Backup/Backup.vue
#### How should this be manually tested?
generate backup file
#### Any background context you want to provide?
this is without password check and ui flow, just for show integration
merge after https://github.com/bitshares/vuex-bitshares/pull/58
#### What are the relevant tickets?
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
#### Questions:

2018-12-14 06:59 UTC, roma219 commented
@ololokiras Can't login with this file:
![image](https://user-images.githubusercontent.com/4411295/49988216-fc655500-ff86-11e8-92ca-dc1343b06d25.png)

2018-12-14 07:39 UTC, roma219 requested changes
The saved file is empty and cannot be used to login :(

2018-12-14 14:51 UTC, ololokiras commented
fixed

2018-12-16 21:50 UTC, roma219 approved these changes

2018-12-16 21:50 UTC, merged