266 neworder circles
bitshares/bitshares-community-ui pull request #283
Opened 2018-12-13 22:39 UTC by lapinlapin

#### What's this PR do?
Added circles components
NewOrderCirclePrice - main circle
NewOrderCircleType - 100/-100
#### Where should the reviewer start?
views/NewOrder/
#### How should this be manually tested?
https://localhost:8080
#### Any background context you want to provide?
#### What are the relevant tickets?
#266 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/6066637/49971844-f056a480-ff40-11e8-96ed-173247a5ac9e.png)

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-266-neworder-circles
#### Questions:

2018-12-14 07:44 UTC, roma219 requested changes
Good, but price inputs needs to be clickable:
![image](https://user-images.githubusercontent.com/4411295/49990016-33d70000-ff8d-11e8-81d1-dd960933ea31.png)

2018-12-14 07:44 UTC, roma219 commented on src/views/NewOrder/NewOrder.vue
> +    <NewOrderCircleType :value="20"/>
Why have it as two instances? Let's make it one instance that has mode="layout" by default

2018-12-14 12:23 UTC, lapinlapin commented on src/views/NewOrder/NewOrder.vue
> +    <NewOrderCircleType :value="20"/>
removed this mode, it is unnecessary here

2018-12-15 09:50 UTC, roma219 approved these changes

2018-12-15 09:51 UTC, merged