284 withdraw transfer
bitshares/bitshares-community-ui pull request #298
Opened 2018-12-15 17:56 UTC by lapinlapin

#### What's this PR do?
Created flow of Withdraw
#### Where should the reviewer start?
/views/Withdraw
#### How should this be manually tested?
http://localhost:8080/
#### Any background context you want to provide?
#### What are the relevant tickets?
#284 
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-284-withdraw-transfer
#### Questions:

2018-12-17 07:29 UTC, roma219 requested changes
Needs some optimizations

2018-12-17 07:29 UTC, roma219 commented on src/store/modules/withdraw.js
> +  [types.TOGGLE_WITHDRAW_MODAL](state, value) {
value not used

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAddress.vue
> +      validateUser: debounce(this.getUser, 500)
Don't store functions in data. Create this function in `created`

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAddress.vue
> +      if (user.success) {
`this.validUser = user.success`

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +    isAmountValid() {
This function should return `true/false` not error string, use another computed if needed

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +      const isNumeric = () => !isNaN(parseFloat(this.amount)) && isFinite(this.amount)
there is a `type="number"` prop in simple input (see how it is done in NewOrder) that will only allow numbers

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +    <div class="withdraw-title">Withdraw</div>
It is better to be placed in the top component, now you repeat it & it's style in every step. Same goes to container with sm:w-120

2018-12-17 07:29 UTC, roma219 commented on src/views/Withdraw/WithdrawWidget.vue
> +  <Modal
title and container should be here to prevent a lot of code copy-paste

2018-12-17 17:37 UTC, lapinlapin commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +    <div class="withdraw-title">Withdraw</div>
i use scoped, therefore so

2018-12-17 18:27 UTC, lapinlapin commented
@roma219 fixed, except the last

2018-12-18 06:12 UTC, roma219 requested changes
1)
![image](https://user-images.githubusercontent.com/4411295/50135112-17480a00-02a4-11e9-9d88-759f264f4e27.png)
2) 
![image](https://user-images.githubusercontent.com/4411295/50135128-262ebc80-02a4-11e9-9308-57bf1b371c77.png)
3) Should be enabled on mobile as well
![image](https://user-images.githubusercontent.com/4411295/50135449-3d21de80-02a5-11e9-93be-c8068ee9b3e2.png)
4) Confirm should be disabled when checking user is in process
![image](https://user-images.githubusercontent.com/4411295/50135608-cdf8ba00-02a5-11e9-9685-904fe80bc4da.png)

2018-12-18 06:12 UTC, roma219 commented on src/views/Withdraw/Withdraw.vue
> +  .withdraw-container {
no such class here

2018-12-18 06:12 UTC, roma219 commented on src/views/Withdraw/Withdraw.vue
> +          :shadower-height="0"
should have a shadower

2018-12-18 06:12 UTC, roma219 commented on src/views/Withdraw/Withdraw.vue
> +      return this.coins.filter(coin => coin.tokens > 0)
`coin => coin.tokens`

2018-12-18 06:12 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +      if (this.amount === undefined || this.amount === '') {
if (!this.amount) return

2018-12-18 06:14 UTC, lapinlapin commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +      if (this.amount === undefined || this.amount === '') {
no)

2018-12-18 06:18 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +      if (this.amount === undefined || this.amount === '') {
well not return, but still

2018-12-19 07:11 UTC, roma219 requested changes
1) This is the initial display:
![image](https://user-images.githubusercontent.com/4411295/50204161-eb488980-0374-11e9-8dcd-d8189de4a247.png)
For understanding how scrolling works with shadowers see `SortableTable` component
Shadower should be at the bottom aswell.
2) Button should be disabled while fetching for user is in progress, right now i can enter and click confirm on an non existing user
![image](https://user-images.githubusercontent.com/4411295/50204292-53976b00-0375-11e9-86ba-75734a0b5f57.png)
3) Why is button disabled here?
![image](https://user-images.githubusercontent.com/4411295/50204318-63af4a80-0375-11e9-994d-53ef65d78344.png)
4) Title is not style correctly and padding is too big
![image](https://user-images.githubusercontent.com/4411295/50204379-a83ae600-0375-11e9-9712-d489162031db.png)
5) Button is not placed correctly on mobile
![image](https://user-images.githubusercontent.com/4411295/50204418-ce608600-0375-11e9-83a6-d340f9ad58d6.png)

2018-12-19 07:11 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAddress.vue
> +      if (user.success) {
No need for this condition, straight `this.validUser = user.success` as it's just gonna make it true/false

2018-12-19 07:11 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +      if (+this.amount <= 0 || +this.amount > this.withdrawAsset.tokens) {
Can make it even shorter:
`return !!(+this.amount <= 0 || +this.amount > this.withdrawAsset.tokens)`

2018-12-19 07:11 UTC, roma219 commented on src/views/Withdraw/WithdrawFinish.vue
> +        disabled="true"
?

2018-12-19 07:11 UTC, roma219 commented on src/views/Withdraw/WithdrawConfirmAmount.vue
> +        :disabled="isAmountValid"
So it should be named `isAmountInvalid` i guess

2018-12-20 06:38 UTC, roma219 approved these changes

2018-12-20 06:38 UTC, merged