281 market orders
bitshares/bitshares-community-ui pull request #301
Opened 2018-12-17 06:30 UTC by youaresofunny

#### What's this PR do?
Integrates market orders (and confirmation)
#### Where should the reviewer start?
NewOrder.vue component
#### How should this be manually tested?
Go to market, chose market order and place it)
#### Any background context you want to provide?
Nope
#### What are the relevant tickets?
Closes https://github.com/bitshares/bitshares-community-ui/issues/281
#### Screenshots (if appropriate)
![selection_019](https://user-images.githubusercontent.com/1954900/50070225-4dbb5180-01de-11e9-8474-5b4ddb913f5c.png)
![selection_020](https://user-images.githubusercontent.com/1954900/50070226-4dbb5180-01de-11e9-94f5-0da4a0d4e26c.png)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/

2018-12-18 06:03 UTC, roma219 requested changes
Needs more limitations so that `Price` and `Get` inputs never display any values. Also has some conflicts @ `vuex-bitshares`

2018-12-18 06:03 UTC, roma219 commented on src/store/modules/newOrder.js
> +  price: 0,
why 0? null is so that input displays placeholder

2018-12-18 08:47 UTC, youaresofunny commented on src/store/modules/newOrder.js
> +  price: 0,
I reworked it, so now it displays on 0 
That because we need to put 0 into confirm order modal sometimes (not null)

2018-12-18 08:53 UTC, youaresofunny commented
@roma219 what are the ways to get smth shown in `Price` or `Get` fields?

2018-12-18 09:13 UTC, roma219 commented
@youaresofunny There are computed values in `NewOrder.vue` component for titles and values of all inputs. So you can use them. You can also use `:placeholder` props in each `SimpleInput` as well. Part of my prev review got lost( The message was to also check this condition in other set actions and also in set order action (which is called clicking on order book order item)
![image](https://user-images.githubusercontent.com/4411295/50143657-453a4800-02be-11e9-9e92-15798167f4c1.png)

2018-12-21 12:11 UTC, youaresofunny commented
@roma219 updated

2018-12-22 08:41 UTC, roma219 approved these changes

2018-12-22 08:41 UTC, merged