#306 disable sort in table
bitshares/bitshares-community-ui pull request #316
Opened 2018-12-17 21:07 UTC by Keegan-lee

#### What's this PR do?
- Implements new property on header columns that will enable/disable the sorting of the column
- Enforces the default cursor for a disabled header, indicating no available click.

#### Where should the reviewer start?
- SortableTable.vue

#### How should this be manually tested?
- Make sure the OrderBook tables sorting functionality can be enabled/disabled by toggling the sortDisabled value passed in OrderBook.vue

#### Any background context you want to provide?
#### What are the relevant tickets?
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
#### Questions:
- Does the Trusty team have any restrictions on the use of the ```!important``` flag on css rules?

2018-12-17 21:11 UTC, lapinlapin commented on src/components/SortableTable/SortableTable.vue
> +  .headerDisabled {
.header, disabled is mod.
header--disabled

2018-12-17 21:11 UTC, lapinlapin commented on src/components/SortableTable/SortableTable.vue
> +    cursor: default !important;
no good **!important**

2018-12-17 21:12 UTC, lapinlapin commented on src/components/SortableTable/SortableTable.vue
> +        :class="{ headerDisabled : header.disableSort }"
what are the gaps?
headerDisabled : -> headerDisabled:

2018-12-17 21:14 UTC, lapinlapin commented on src/components/SortableTable/SortableTable.vue
> +      console.log(header)
remove logs please

2018-12-18 02:07 UTC, Keegan-lee commented on src/components/SortableTable/SortableTable.vue
> +        :class="{ headerDisabled : header.disableSort }"
Do you mean "-" by gaps?

2018-12-18 02:07 UTC, Keegan-lee commented on src/components/SortableTable/SortableTable.vue
> +    cursor: default !important;
I'll make a change.

2018-12-18 06:50 UTC, roma219 requested changes
Ok, just needs a minor class renaming

2018-12-18 06:50 UTC, roma219 commented on src/components/SortableTable/SortableTable.vue
> +  .headerDisabled {
@Keegan-lee We use a convention for class naming, so any modification (state) classes are written like `.header--disabled` Please rename

2018-12-18 19:28 UTC, roma219 approved these changes

2018-12-18 19:34 UTC, merged