#320 Fix Sortable Tables
bitshares/bitshares-community-ui pull request #321
Opened 2018-12-18 22:42 UTC by Keegan-lee

#### What's this PR do?
- Revamped sorting mechanism to fix the issue
- Fixes the broken sortability

#### Where should the reviewer start?
- SortableTable.vue
#### How should this be manually tested?
Make sure that the tables can be toggled programmatically. Toggle a sortable table on/off and make sure that the tables remain sortable.

#### Any background context you want to provide?
- This is a fix for ticket #306 
#### What are the relevant tickets?
- #306, #320 
#### Screenshots (if appropriate)
#### URL
#### Questions:

2018-12-19 07:16 UTC, roma219 requested changes
Improvement suggested

2018-12-19 07:16 UTC, roma219 commented on src/components/SortableTable/SortableTable.vue
> +      let header = this.headers.find(h => h.field === field) || {}
I think this kind of check should be performed inside `SortableHeaderItem` - the event should not be emitted if sorting is disable.

2018-12-21 18:08 UTC, Keegan-lee commented on src/components/SortableTable/SortableTable.vue
> +      let header = this.headers.find(h => h.field === field) || {}
I agree! I figured out how to do this elsewhere.

2018-12-22 08:36 UTC, roma219 approved these changes

2018-12-22 08:36 UTC, roma219 commented on src/components/SortableHeaderItem/SortableHeaderItem.vue
> +    disableSort: {
I don't think you need this prop as you already have access to `header` object as `item`

2018-12-22 08:37 UTC, merged