295 search imp
bitshares/bitshares-community-ui pull request #325
Opened 2018-12-19 00:59 UTC by lapinlapin

#### What's this PR do?
Improvements editing
#### Where should the reviewer start?
components/searchInput
#### How should this be manually tested?
http://localhost:8080
#### Any background context you want to provide?
#### What are the relevant tickets?
#295 
#### Screenshots (if appropriate)
#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/branch-295-search-imp
#### Questions:

2018-12-19 01:05 UTC, lapinlapin commented on src/components/SearchInput/SearchInput.vue
> +        @click="$emit('input', $event.target.value)"
@roma219 help me please in this moment.. this click not work, click.native too

2018-12-19 07:34 UTC, roma219 requested changes
The search input should not disapper when it is focused and mouse is moved away

2018-12-19 07:34 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +        @click="$emit('input', $event.target.value)"
Well, $event.target  for this click event is icon, it doesn't have any value. You probably want to emit an empty string to clear the input.

2018-12-20 08:36 UTC, roma219 requested changes
![image](https://user-images.githubusercontent.com/4411295/50273255-36cd6700-044b-11e9-89a8-41c976d6cb01.png)
Please remove word "Search" from placeholder

2018-12-20 08:36 UTC, roma219 commented on src/components/SearchInput/SearchInput.vue
> +        @click="$emit('input', ''); value = ''"
![image](https://user-images.githubusercontent.com/4411295/50248539-67ca7f00-03ec-11e9-99c3-a34b48f7750c.png)
?

2018-12-20 08:46 UTC, lapinlapin commented on src/components/SearchInput/SearchInput.vue
> +        @click="$emit('input', ''); value = ''"
1. emit - for a vuex search from str and update state
2. value = '' for a reset value in this input

2018-12-22 08:49 UTC, roma219 approved these changes

2018-12-22 08:49 UTC, merged