wip: Tabs
bitshares/bitshares-community-ui pull request #42
Opened 2018-09-26 15:01 UTC by MindfulMe

#### What's this PR do?
The PR adds tabs component

#### Where should the reviewer start?
at Tabs.vue

#### How should this be manually tested?
The component is being used on the main page

#### Any background context you want to provide?
Work in progress, will be finished in several hours

#### What are the relevant tickets?
Tabs component

#### Screenshots (if appropriate)
Preview: 
<img width="275" alt="screen shot 2018-09-26 at 17 59 08" src="https://user-images.githubusercontent.com/26275425/46088818-e9c45680-c1b5-11e8-861f-735702da46e8.png">

#### Questions:
Can you describe how do you want to pass the content of the tabs if not through props?

2018-09-26 15:02 UTC, MindfulMe commented
Note: I will remove vuex dependency later, because I can't launch the development server

2018-09-26 15:12 UTC, roma219 commented
> Can you describe how do you want to pass the content of the tabs if not through props?
Like that
```
<Tabs :titles>
   <div slot="one"> ... </div>
<div slot="one"> ... </div>
<div slot="one"> ... </div>
<Tabs/>
```

2018-09-26 16:34 UTC, roma219 commented
[Named slots docs](https://vuejs.org/v2/guide/components-slots.html#Named-Slots)

2018-09-26 16:47 UTC, roma219 requested changes
See comments

Please use tailwind css variables for colors, fonts and font-sizes ( check out `./tailwind.js` file the list and tailwind docs for 'how to')

Will do a more thoughtful review later

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +<div id="tabs" class="container">
no need for `id` attribute, and probably no need for a `container` class - it's a special util class in tailwind and is already used in App.vue (main container), so no need for the second. Just use `tabs` as a class

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +        <a  v-bind:key=key v-for="(title, key) in titles" v-on:click="activetab=title" v-bind:class="[ activetab === title ? 'active' : '' ]">{{title}}</a>
1) You don't need to write `v-bind` every time, just use `:key`, `:class` etc
2) Same for `v-on` -> you can use `@click`
3) More the two arrtibutes -> write them as a column

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +    activetab: {
Please use camelCase for variable names

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +* {
what is this?

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +.tabs a {
It's probably better to use block element instead of `<a>`. Each tab should take up equal amount of width.

2018-09-26 16:47 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +.container {
No need for max and min width and margins - Component should take up all availible width. And no margins as well.

2018-09-29 11:37 UTC, roma219 requested changes
![image](https://user-images.githubusercontent.com/4411295/46245339-d521d180-c3f4-11e8-8030-df06a05314f0.png)
Please provide some actually usable examples and not this.

Also add a prop (`:centered="true`) that makes tabs centered when provided, left-aligned otherwise.

See comments

2018-09-29 11:37 UTC, roma219 commented on .gitignore
> +package-lock.json
We shouldn't gitignore package-lock file, best practice is to [check it in](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5)

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +          <a
Don't use '<a>' element if it's not a link

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +            @click="(e) => activeTab = tab"
no need for `e` argument, if you don't use it

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +    tabs: Array
activeTab should be a prop

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      <slot :name="tab" v-for="tab in tabs" v-if="tab === activeTab" />
No need for `v-if` here. Actually you shouldn't use `v-for` with `v-if` together at all, use computed properties instead.

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      activeTab: this.tabs[0]
you should never assign prop to data

2018-09-29 11:37 UTC, roma219 commented on src/views/Main.vue
> +      <Tabs :tabs="['Tab example #1 with the responsive width', 'Tab example #2 with the responsive width', 'Tab example #3 with the responsive width']">
Don't put it into Main.vue, use Components.vue instead for this kind of testing.

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +    color:DarkGrey;
Use tailwind.js colors and paddings, use existing config ones or create new (like `color: config('colors.text-primary');`) (see tailwind.js)

2018-09-29 11:37 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  margin-bottom: -2px;
No need for this margins

2018-09-30 18:31 UTC, MindfulMe commented
review, merge please

2018-10-01 08:30 UTC, roma219 requested changes
Do not delete/edit files that do not correspond with the task, please revert your last changes, you probably need to merge staging into your branch.

2018-10-01 08:30 UTC, roma219 commented on .eslintrc.js
> +    'plugin:vue/essential',
return recommended

2018-10-01 08:30 UTC, roma219 commented on .eslintrc.js
> +    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off'
return this rule

2018-10-01 18:29 UTC, roma219 requested changes
Needs to be changed

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.md
> +      <Tabs :active="['Tab example #1']" :crentered=true :tabs="['Tab example #1', 'Tab example #2', 'Tab example #3', 'Tab example #4']">
crentered

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.md
> +      <Tabs :crentered=true :tabs="['Tab example #1', 'Tab example #2', 'Tab example #3', 'Tab example #4']">
crentered

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +span:visited {
what is this?

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  margin-left: 20px;
why margin-left?

2018-10-01 18:29 UTC, roma219 commented on src/views/Components.vue
> -  data() {
why are you removing that?

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +            href="#"
href?

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +            @click="() => activeTab = tab"
no need for a func, can be done like `@click="activeTab = tab"`

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  width:100%;
block element has 100% width by default

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  width: 100%;
block element has 100% width by default

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      default: function() {
() => []

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      default: function() {
why active is an array?

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +.center {
this class won't center it's content

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +<style lang="scss">
make it scoped

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +.tabContent {
`.tabs-content` - keep consistency in naming

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      return this.tabs.map((tab) => {
why are you using `map`? you can just calculate the name of the current tab

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +        v-for="tab in filteredTabs"
Do you need this cycle here? You are only displaying one tab at a time, just make a computed value for an activeTab

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      activeTab: this.active[0]
do not refer data variable to prop variable. Ok, just rename it to `activeTabIndex` and make it 0. (`remove the active` prop at all)

2018-10-01 18:29 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  color: config('colors.grey');
please use semantic color names for tailwind.js. Right now it has the 'text-primary' color, use it and create additional for tabs, like `tab-border`, `tab-active-border`, `tab-color`, `tab-active-color`

2018-10-01 19:27 UTC, roma219 commented
@MindfulMe also add `process` tag to issue you are working on a `wip:` prefix to PR

2018-10-01 19:29 UTC, MindfulMe commented
yep

2018-10-01 19:57 UTC, MindfulMe commented
review 👐

2018-10-01 20:14 UTC, roma219 commented
@MindfulMe Still has stuff you didn't fix. see Changes tab.

2018-10-02 06:33 UTC, roma219 requested changes
Still has unfixed stuff

2018-10-02 06:33 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      activeTab: this.tabs[0]
fix please

2018-10-02 06:33 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +* {
remove please

2018-10-02 10:05 UTC, MindfulMe commented
` activeTab: this.tabs[0]` is the first tab selector by default, before it came from props

2018-10-02 10:07 UTC, MindfulMe commented
`<style lang="css">` had been fixed already, I have just checked tabs branch - it is fine

2018-10-02 10:10 UTC, roma219 requested changes

2018-10-02 10:10 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  flex-direction:row;
it is row by default, no need to specify it

2018-10-02 10:10 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  margin-left: -40px;
what this margins are for?

2018-10-02 10:12 UTC, MindfulMe commented on src/components/Tabs/Tabs.vue
> +  margin-left: -40px;
I believe this margin to balance the padding from here `  padding: 12px 24px;` and here `padding: 30px 30px 30px 30px;`, so actually it should be -42px

2018-10-02 10:13 UTC, MindfulMe commented on src/components/Tabs/Tabs.vue
> +  margin-left: -40px;
otherwise the is biased to the right

2018-10-02 10:41 UTC, MindfulMe commented on src/components/Tabs/Tabs.vue
> +  margin-left: -40px;
maybe you have any other suggestions

2018-10-02 18:25 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +      activeTab: this.tabs[0]
just change it to `activeTabIndex: 0`

2018-10-02 18:26 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  display: -webkit-flex;
No need for browser specific prefixes, they'll be auto-generate, just leave `display: flex`

2018-10-02 18:28 UTC, roma219 commented on src/components/Tabs/Tabs.vue
> +  margin-left:-40px;
this margin is not needed, just set `padding: 0` to `ul`

2018-10-02 18:29 UTC, roma219 commented
@MindfulMe 
![image](https://user-images.githubusercontent.com/4411295/46368705-8a6cb780-c689-11e8-8d4f-7e9492936b12.png)

![image](https://user-images.githubusercontent.com/4411295/46368773-b25c1b00-c689-11e8-8218-fbb8c9aff146.png)

![image](https://user-images.githubusercontent.com/4411295/46368828-e0d9f600-c689-11e8-8d88-d0a783d68ab4.png)

![image](https://user-images.githubusercontent.com/4411295/46368932-2d253600-c68a-11e8-9dfb-0970d3ed4d4d.png)

2018-10-03 15:58 UTC, MindfulMe commented
done

2018-10-03 16:25 UTC, roma219 commented
@MindfulMe Tabs are not centered. You must test yourself all the possible cases before submitting PR for review.

![image](https://user-images.githubusercontent.com/4411295/46424498-fc083c80-c741-11e8-8ea8-a8d38e1f00b3.png)

2018-10-03 16:48 UTC, MindfulMe commented
done, centered & tested

2018-10-03 17:03 UTC, MindfulMe commented
<img width="813" alt="screen shot 2018-10-03 at 20 02 58" src="https://user-images.githubusercontent.com/26275425/46426473-6374bb00-c747-11e8-968a-9bc20dd64c52.png">

2018-10-03 17:03 UTC, MindfulMe commented
`justify-content: center;`

2018-10-03 17:05 UTC, MindfulMe commented
the background should be dark so the tabs will fit the theme

2018-10-03 17:05 UTC, roma219 commented
@MindfulMe Now it won't be centered when passing :centered="false"

2018-10-03 17:07 UTC, MindfulMe commented
they should be always at the center?

2018-10-03 17:09 UTC, MindfulMe commented
when using 4, 6, 8, 10 ... tabs they were centered by default, so what is the reason to use :centered prop

2018-10-03 17:10 UTC, MindfulMe commented
I can display them as a column and align to left, or just align to the left while centered is not passed

2018-10-03 17:11 UTC, roma219 commented
@MindfulMe Finally it's ok

2018-10-03 17:11 UTC, roma219 approved these changes

2018-10-03 20:09 UTC, merged