13 input component
bitshares/bitshares-community-ui pull request #43
Opened 2018-09-26 17:42 UTC by roma219

#### What's this PR do?
Creates Input.vue - UI Component
#### Where should the reviewer start?
components/Input/
#### How should this be manually tested?
check out `/components` route for different use-cases of the component
#### Any background context you want to provide?
Will need a stronger integration with tailwind in future
#### What are the relevant tickets?
#13 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/4411295/46097825-8d6c3180-c1cb-11e8-8927-cb10ba085197.png)
![image](https://user-images.githubusercontent.com/4411295/46097872-ad035a00-c1cb-11e8-95d9-2d6d52d7ea52.png)

#### Questions:
n/a/

2018-09-27 20:22 UTC, youaresofunny commented
While we are waiting for webhook to be set, build for this pr can be found here:
http://staging-ui.trusty.apasia.tech:8080/13-input-component/#/components

2018-09-27 20:26 UTC, youaresofunny commented on src/assets/svg/copy.svg
> +</g>
Cleanup this `<g></g><g></g>` 's please

2018-09-27 20:29 UTC, youaresofunny requested changes
Password input doesn't hide it's content

2018-09-27 20:29 UTC, youaresofunny commented on src/components/Button/Button.vue
> +    @click="$emit('click')"
What is this emit for?

2018-09-28 05:32 UTC, roma219 commented on src/assets/svg/copy.svg
> +</g>
This is an `.svg` file with icon...

2018-09-28 05:34 UTC, roma219 commented on src/components/Button/Button.vue
> +    @click="$emit('click')"
So that you could use Button like this `<Button ... @click="handleAction"/> (without child-emitting you could do it by @click.native, but this way it's cleaner)

2018-09-28 06:09 UTC, roma219 commented
@youaresofunny commented on you questions & added `password` type support

2018-09-28 06:12 UTC, youaresofunny submitted a review, later dismissed

2018-09-28 23:38 UTC, hisinbox commented
please amend vertical centring inside the field by the capital letters, and not regular letters

2018-09-29 12:03 UTC, roma219 commented
@hisinbox fixed
![image](https://user-images.githubusercontent.com/4411295/46245587-b6253e80-c3f8-11e8-9d29-ed77ad55469c.png)

2018-09-30 16:21 UTC, youaresofunny approved these changes

2018-09-30 16:32 UTC, roma219 commented
@hisinbox @dls-cipher merge please

2018-09-30 17:29 UTC, merged