user info component
bitshares/bitshares-community-ui pull request #48
Opened 2018-09-30 14:28 UTC by ololokiras

#### What's this PR do?
show user info component in header
#### Where should the reviewer start?
src/views/UserInfo.vue
#### How should this be manually tested?
See account icon, account name and arrow in Header
#### Any background context you want to provide?
Nope
#### What are the relevant tickets?
closes #30 
#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/17277287/46258592-e0edc080-c4e6-11e8-91ae-6913d1384c3d.png)
#### Questions:
How import icons in combine style?

2018-09-30 16:12 UTC, roma219 submitted a review, later dismissed
👍

2018-09-30 16:13 UTC, roma219 commented
@dls-cipher @hisinbox merge please

2018-09-30 17:30 UTC, hisinbox commented
This branch has conflicts that must be resolved

2018-09-30 20:15 UTC, ololokiras commented
@hisinbox fixed

2018-09-30 21:28 UTC, roma219 requested changes
Needs a couple smallfixes, otherwise good

2018-09-30 21:28 UTC, roma219 commented on src/views/Header.vue
> -    display: flex;
why delete? this is made to align header content

2018-09-30 21:28 UTC, roma219 commented on src/views/UserInfo.vue
> +    <p>{{ getName }}</p>
Can do it simplier `{{ userName || 'default' }}` - and you won't need computed for this

2018-10-01 08:01 UTC, roma219 approved these changes
👍

2018-10-01 14:53 UTC, hisinbox commented
looks good. will update design in due course

2018-10-01 14:53 UTC, merged