Card ui
bitshares/bitshares-community-ui pull request #55
Opened 2018-10-05 18:24 UTC by MindfulMe

#### What's this PR do?
Adds a Card-UI component
#### Where should the reviewer start?
At Card.vue
#### How should this be manually tested?
go to localhost:8080/#/components
#### Any background context you want to provide?
No
#### What are the relevant tickets?
Card-UI component
#### Screenshots (if appropriate)
#### Questions:
I can't find any mockup related to Card-UI component on Zeplin, does it exist?

2018-10-05 18:35 UTC, roma219 requested changes
> I can't find any mockup related to Card-UI component on Zeplin, does it exist?

Yes, check out Markets and Order book widgets - the idea is to use this Card UI component to display further widgets.

2018-10-05 18:35 UTC, roma219 commented on src/components/Card/Card.vue
> +    :class="{
No need for dark/light themes in components. Theme switching gonna be implemented in a tailwindcss layers - that's why we use it's varialbes for colors

2018-10-05 18:35 UTC, roma219 commented on src/components/Card/Card.vue
> +      {{ title }}
title should be in the header

2018-10-05 18:35 UTC, roma219 commented on src/components/Card/Card.vue
> +      default: () => ''
No need for defaul funcs in string props

2018-10-05 18:35 UTC, roma219 commented on src/components/Card/Card.vue
> +  background-color: config('colors.card-background-dark');
just use `card-background` and when changing dark/light it is gonna change in a wailwind config layer

2018-10-05 18:35 UTC, roma219 commented on src/views/UserInfo.vue
> +// import '@icons/userIcon'
why that? You probably need to run `npm run svg` before starting

2018-10-07 15:43 UTC, roma219 commented on src/components/Card/Card.vue
> +  font-family: Gotham_Pro_Regular;
there is a tailwind variables with font families - and you won't need font-weight for that

2018-10-07 15:45 UTC, MindfulMe commented on src/components/Card/Card.vue
> +  font-family: Gotham_Pro_Regular;
got it

2018-10-07 17:27 UTC, roma219 commented
![image](https://user-images.githubusercontent.com/4411295/46584711-3e49ba80-ca6f-11e8-88dc-ee720223d3ed.png)
 
Should look identicatal to this:
![image](https://user-images.githubusercontent.com/4411295/46584723-5faaa680-ca6f-11e8-98d1-5f1fde648abb.png)

![image](https://user-images.githubusercontent.com/4411295/46584729-73560d00-ca6f-11e8-95fc-111a2c124baf.png)

2018-10-07 18:47 UTC, roma219 commented
@MindfulMe And from now on the main development branch is `dev` - so use it to branch out from and to make PRs to.

2018-10-08 13:54 UTC, MindfulMe commented
What else should be added, I just placed components that come to slot tags to the right positions. Because I guess the search box and other interesting stuff is just some components that will be passed via slots

2018-10-08 13:56 UTC, MindfulMe commented
font sizes from zeplin does not match the page sizes anyways 🙄

2018-10-08 14:52 UTC, roma219 commented
@MindfulMe paddings, bg color, title styles

2018-10-08 14:55 UTC, MindfulMe commented
also, I think I can pull&merge changes from dev and make a pull request directly to dev

2018-10-08 14:55 UTC, roma219 commented
@MindfulMe just edit this PR

2018-10-08 14:57 UTC, MindfulMe commented
okay..)

2018-10-08 15:57 UTC, MindfulMe commented
Is it okay?<img width="1066" alt="screen shot 2018-10-08 at 18 56 58" src="https://user-images.githubusercontent.com/26275425/46619922-03f22300-cb2c-11e8-928d-ac1b95f9a4dc.png">

2018-10-08 16:16 UTC, MindfulMe commented
This is exactly according to Zeplin<img width="1067" alt="screen shot 2018-10-08 at 19 15 41" src="https://user-images.githubusercontent.com/26275425/46620855-972c5800-cb2e-11e8-858c-47dd0e3f2ca2.png">

2018-10-08 16:20 UTC, MindfulMe commented
Exactly according to Zeplin<img width="1066" alt="screen shot 2018-10-08 at 19 20 08" src="https://user-images.githubusercontent.com/26275425/46621091-38b3a980-cb2f-11e8-968c-45afc83bc720.png">

2018-10-08 19:44 UTC, roma219 commented
@MindfulMe 
![image](https://user-images.githubusercontent.com/4411295/46630080-bb4a6200-cb4b-11e8-9a90-2f80285d235b.png)

2018-10-08 20:07 UTC, MindfulMe commented
yep 👍

2018-10-08 20:29 UTC, roma219 requested changes
Small fixes

2018-10-08 20:29 UTC, roma219 commented on tailwind.js
> +  'text-primary': '#000000',
it is already defined

2018-10-08 20:29 UTC, roma219 commented on tailwind.js
> +  'card-text': '#ffffff',
use 'text-primary' instead

2018-10-08 20:29 UTC, roma219 commented on tailwind.js
> +    'card-ui': '11px',
use rems

2018-10-08 20:29 UTC, roma219 commented on tailwind.js
> +    'card-ui-header': '27px'
rems

2018-10-08 20:29 UTC, roma219 commented on src/components/Card/Card.vue
> +        <div> {{ upper(title) }} </div>
You can do it via css

2018-10-08 20:30 UTC, MindfulMe commented on src/components/Card/Card.vue
> +        <div> {{ upper(title) }} </div>
got it

2018-10-09 06:07 UTC, roma219 commented
@MindfulMe next time write use number of issue in branchname and in PR name. Also you can reference it like "closes #52" in PR message to automatically close it when PR is accepted.

2018-10-09 06:07 UTC, roma219 approved these changes

2018-10-09 06:07 UTC, merged