wip: 50 keyfile loader
bitshares/bitshares-community-ui pull request #56
Opened 2018-10-08 12:20 UTC by ololokiras

#### What's this PR do?
Create auth by file. Create UI and auth by file vuex calls
#### Where should the reviewer start?
src/views/Login/KeyfileLoader.vue
#### How should this be manually tested?
See button for upload file in "Private key" tab in Login
#### Any background context you want to provide?
nope
#### What are the relevant tickets?
#50 
#### Screenshots (if appropriate)
it's weird yet, need some repair
#### Questions:
Will we use hard width value, or prefer 100%? 
Cause I use px for set width of button, and @roma219 use all width (like width:100%). And now will repair it for Roman's style.

2018-10-10 17:30 UTC, roma219 requested changes
Needs cleanup and some changes + actual integration into Login

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +      this.$refs.fileform.addEventListener('drop', e => {
This can be done in template - like `<form @drop="handleDrop" ...`

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +import { mapActions } from 'vuex'
is it needed?

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +    ...mapActions({
it is not needed here

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +    emitFile(file) {
please separate it into several functions, because function with a name `emitFile` should not be reading it

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +        this.$emit('select', {
it should be emitted only on successful load

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +    determineDragAndDropCapable() {
what is this? :0

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/Login.vue
> +          <KeyfileLoader/>
add ` @select="selectFile"` and `selectFile` method that would save file in a component's `data`

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +    flex-direction: row;
it is `row` by default

2018-10-10 17:30 UTC, roma219 commented on src/views/Login/KeyfileLoader.vue
> +    color: #fff200;
use tailwind css variables as least for colors - see `Input` component for examples. You probably'll only need existing variables from it.

2018-10-10 17:31 UTC, roma219 commented
@ololokiras Also it seems i cannot delete the file - clicking the X icon does nothing

2018-10-10 17:33 UTC, roma219 commented
@ololokiras Also drag'n'drop display is blicking when file is hovered over and it should check for correct file type after dropping/file reading
![image](https://user-images.githubusercontent.com/4411295/46754689-ba403e80-cccb-11e8-8c4e-8e339f9e5346.png)

2018-10-10 18:16 UTC, ololokiras commented on src/views/Login/KeyfileLoader.vue
> +    determineDragAndDropCapable() {
it's check for available to drag and drop for browser

2018-10-11 16:27 UTC, youaresofunny requested changes
![screenshot_20181011-212328](https://user-images.githubusercontent.com/1954900/46819133-5f2a4c80-cd9c-11e8-9b18-333a51dd684d.jpg)
 Also nothing happens when I select wrong file there

2018-10-12 23:26 UTC, mindfulme requested changes
It would be better to center the file input and make it responsive for extra small screens

<img width="482" alt="screen shot 2018-10-13 at 02 22 31" src="https://user-images.githubusercontent.com/26275425/46898047-35058700-ce8f-11e8-8ae5-e23171e69594.png">

2018-10-13 09:19 UTC, merged