Portfolio
bitshares/bitshares-community-ui pull request #61
Opened 2018-10-11 00:06 UTC by MindfulMe

#### What's this PR do?
Adds Portfolio table component
#### Where should the reviewer start?
From Portfolio.vue 
#### How should this be manually tested?
Go to Dashboard components `http://localhost:8080/#/`
#### Any background context you want to provide?
No
#### What are the relevant tickets?
Basic Portfolio Markup
#### Screenshots (if appropriate)
<img width="750" alt="screen shot 2018-10-11 at 03 04 11" src="https://user-images.githubusercontent.com/26275425/46772818-9c420080-cd02-11e8-9994-18704bc09d97.png">
<img width="922" alt="screen shot 2018-10-11 at 03 04 19" src="https://user-images.githubusercontent.com/26275425/46772821-9e0bc400-cd02-11e8-8e5c-acbda352ff90.png">

#### Questions:
How to pass data to the table? Via props?

2018-10-11 05:06 UTC, roma219 requested changes
Don't use `<table>`. Use grid instead. Portfolio is a view and should be in a View folder. You should have `Portfolio`, `PortfolioHeader`, `PortfolioItem` components.

2018-10-11 05:06 UTC, roma219 commented on src/components/Portfolio/Portfolio.vue
> +    <table>
No tables - use grid instead, css or tailwind has capabilities - https://tailwindcss.com/docs/examples/grids

2018-10-11 05:06 UTC, roma219 commented on src/components/Portfolio/Portfolio.vue
> +  border-right: 10px solid config('colors.table-bg');
tables-bg ? it is not background

2018-10-11 05:06 UTC, roma219 commented on src/components/Portfolio/Portfolio.vue
> +  border-bottom: 10px solid config('colors.table-bg');
30px border?

2018-10-11 05:06 UTC, roma219 commented on src/views/Dashboard.vue
> +        <Tabs :tabs="['SHOW ALL ASSETS', 'SHOW BALANCES']">
No need for tabs

2018-10-11 05:34 UTC, roma219 commented
Also you removed some part with the url from the PR message.

> #### URL
> Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/

2018-10-11 05:44 UTC, roma219 commented
Also read https://github.com/bitshares/bitshares-community-ui/blob/staging/docs/dev-guide.md and fix this branch/pr

2018-10-12 15:58 UTC, MindfulMe commented
@roma219 quick review please <img width="413" alt="screen shot 2018-10-12 at 18 32 30" src="https://user-images.githubusercontent.com/26275425/46880206-b2f66d80-ce50-11e8-87d9-8cb1de7ab006.png">

2018-10-12 16:58 UTC, roma219 requested changes
See comments. The Data will be an array of objects, similar to this: 
```
[{
 name: 'BTC',
 token: 0.345,
 fiatValue: 2345,
percent: 12
}, {
...
}]
```
You should render `PortfolioItem` components inside `Portfolio` interating over this array with `v-for`

2018-10-12 16:58 UTC, roma219 commented on .gitignore
> +Procfile
what is this?

2018-10-12 16:58 UTC, roma219 commented on src/views/Portfolio/Portfolio.vue
> +.grid > span > strong {
Better use semantic class selectors instead
`.portfolio-table .header-item`

2018-10-12 16:58 UTC, roma219 commented on src/views/Portfolio/PortfolioHeader.vue
> +.textWeak {
.text-weak

2018-10-12 16:58 UTC, roma219 commented on src/views/Portfolio/PortfolioHeader.vue
> +  <div class="portfolio">
Don't make class duplications, name is semanticly, like 'portfoli-header`

2018-10-12 16:59 UTC, roma219 commented
Also:
![image](https://user-images.githubusercontent.com/4411295/46883021-4764ce00-ce59-11e8-9786-e47273d117df.png)
Provide a link, rename branch and PR

2018-10-12 21:12 UTC, MindfulMe commented
<img width="1204" alt="screen shot 2018-10-13 at 00 11 16" src="https://user-images.githubusercontent.com/26275425/46894270-92440d00-ce7c-11e8-8098-058649b4878c.png">

http://staging-ui.trusty.apasia.tech:8080/portfolio/#/

2018-10-12 23:18 UTC, MindfulMe commented
@roma219 I only didn't rename the branch name as it causes the PR to be closed automatically, everything else should be fine

2018-10-13 08:05 UTC, roma219 commented
@MindfulMe 
![image](https://user-images.githubusercontent.com/4411295/46903024-d6b0c680-ced7-11e8-96ef-36082070bd27.png)
Should be aligned

2018-10-13 10:02 UTC, roma219 requested changes
@MindfulMe This task needs to be done asap

2018-10-13 10:02 UTC, roma219 commented on Procfile
> +Web: 'rpm run serve'
what is this?

2018-10-13 10:02 UTC, roma219 commented on src/views/Dashboard.vue
> +            <div slot="item">
You don't need slot in Portfolio, no components are gonna be placed like that inside portfolio
PortfolioItem should represent 1 row that is rendered via `v-for` inside `Portfolio`

2018-10-13 10:02 UTC, roma219 commented on src/views/Portfolio/PortfolioItem.vue
> +      v-for="(item, index) in items"
PortfolioItem should be just 1 row and the iterated over in Portfolio, like this:
`<PortfolioItem v-for="(item, index) in items" :item="item" />

2018-10-13 10:02 UTC, roma219 commented on src/views/Portfolio/PortfolioItem.vue
> +  data() {
This data should be in Portfolio and send to each PortfolioItem via props

2018-10-13 10:02 UTC, roma219 commented on src/views/Portfolio/PortfolioItem.vue
> +@media screen and (max-width: 990px) {
No need for media queries for now, at this point we only need a basic table. Also, see https://tailwindcss.com/docs/responsive-design

2018-10-13 11:19 UTC, mindfulme commented
okay, got it

2018-10-13 11:40 UTC, MindfulMe commented
@roma219 done, now I guess I should review everything once more

2018-10-13 11:59 UTC, MindfulMe commented
reviewed - now must be ok, responsive with the iteration as needed

2018-10-13 12:29 UTC, roma219 requested changes
small fix

2018-10-13 12:29 UTC, roma219 commented on src/views/Portfolio/Portfolio.vue
> +    <div
No need for this div, you can iterate over PortfolioItem the same way aka:
`<PortfolioItem v-for ...etc />

2018-10-13 12:34 UTC, roma219 commented
@MindfulMe This should be aligned the same distance from the left like Portoflio title
![image](https://user-images.githubusercontent.com/4411295/46905507-75035300-cefd-11e8-9520-4c8de95f3940.png)

Also the table should take all 100% width

2018-10-13 16:58 UTC, MindfulMe commented
Got it, will apply something better

2018-10-13 17:07 UTC, MindfulMe commented
removed the horizontal padding

2018-10-13 17:37 UTC, roma219 commented
@MindfulMe Fix MR conflict

2018-10-13 17:41 UTC, roma219 requested changes
Return transactions widget and just place you Portfolio components into "Account" widget

2018-10-13 17:41 UTC, roma219 commented on src/views/Dashboard.vue
> -        <TransactionsHistory/>
@MindfulMe  Why did you remove this card with Transactions widget? Fix please

2018-10-13 17:43 UTC, roma219 commented
@MindfulMe Did you actually run the app after merge? There are errors, build is failing:
![image](https://user-images.githubusercontent.com/4411295/46908232-94fc3c00-cf28-11e8-8a7e-6c6b6765006d.png)

2018-10-13 18:04 UTC, roma219 commented
@MindfulMe fix asap

2018-10-13 18:07 UTC, MindfulMe commented
almost done

2018-10-13 18:14 UTC, MindfulMe commented
@roma219 works now

2018-10-13 18:15 UTC, roma219 approved these changes

2018-10-13 18:15 UTC, merged