86 header item component
bitshares/bitshares-community-ui pull request #98
Opened 2018-10-19 23:22 UTC by mindfulme

#### What's this PR do?
Adds header item component for the sortable table
#### Where should the reviewer start?
at HeaderItem.vue
#### How should this be manually tested?
The component is placed at components page
#### Any background context you want to provide?
There is a note from Armen that the sorting arrows should be placed leftward the title
![photo_2018-10-19_11-15-30](https://user-images.githubusercontent.com/26275425/47264117-7eea0f00-d518-11e8-82b4-77e20ba229b8.jpg)

#### What are the relevant tickets?
[#86](https://github.com/bitshares/bitshares-community-ui/issues/86)
#### Screenshots (if appropriate)
<img width="168" alt="screen shot 2018-10-21 at 09 59 08" src="https://user-images.githubusercontent.com/26275425/47264098-fe2b1300-d517-11e8-8bfc-9a49b13d0750.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
[http://staging-ui.trusty.apasia.tech:8080/86-header-item-component ](http://staging-ui.trusty.apasia.tech:8080/86-header-item-component)
#### Questions:
What can be improved?

2018-10-23 17:59 UTC, roma219 requested changes
Needs changes

Also:
1) Rename component to SortableHeaderItem
2) Title should change colors depending on if there is any sort applying or not

2018-10-23 17:59 UTC, roma219 commented on src/components/HeaderItem/HeaderItem.md
> +          <div slot="title">
Why use slot for this? Title is a simple string, `prop` is enough

2018-10-23 17:59 UTC, roma219 commented on src/components/HeaderItem/HeaderItem.vue
> +  color: config('colors.sort-arrow-hover');
is this really some new unique color not used anywhere else? as well as other arrows colors?

2018-10-23 17:59 UTC, roma219 commented on src/components/HeaderItem/HeaderItem.vue
> +  height: 3px;
no px - use rem. https://github.com/MMF-FE/vue-svgicon - how to set width/height of the icon

2018-10-23 17:59 UTC, roma219 commented on src/components/HeaderItem/HeaderItem.vue
> +      default: () => null,
why it defauts to function returning null? Why not just empty string?

2018-10-23 20:03 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.vue
> +  color: config('colors.sort-arrow-hover');
Should be used somewhere else, I previously assumed that it should have the color which describes the element where the color is used

2018-10-23 20:04 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.vue
> +  height: 3px;
this is useful

2018-10-23 20:14 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.vue
> +      default: () => null,
In the issue, it is said to return `null` by default, probably I should have asked about it. Hmm, I guess I got it

2018-10-23 20:15 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.md
> +          <div slot="title">
Okay, though some other content could be passed

2018-10-23 20:41 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.vue
> +  height: 3px;
though they use pixels too
<img width="262" alt="screen shot 2018-10-23 at 23 39 49" src="https://user-images.githubusercontent.com/26275425/47389265-043e1100-d71d-11e8-9a49-97d75e92a31d.png">

2018-10-23 20:44 UTC, MindfulMe commented on src/components/HeaderItem/HeaderItem.vue
> +  height: 3px;
or rather pass from props
<img width="475" alt="screen shot 2018-10-23 at 23 42 43" src="https://user-images.githubusercontent.com/26275425/47389469-7f072c00-d71d-11e8-89f2-05d991939c2f.png">

2018-10-24 04:52 UTC, roma219 requested changes
Small cleanup and ok

2018-10-24 04:52 UTC, roma219 commented on src/components/SortableHeaderItem/SortableHeaderItem.vue
> +      default: () => '',
just `default: ''` is enough
https://vuejs.org/v2/guide/components.html

2018-10-24 12:15 UTC, roma219 approved these changes

2018-10-24 12:16 UTC, merged