wip: 73 Mobile footer
bitshares/bitshares-community-ui pull request #99
Opened 2018-10-20 01:27 UTC by MindfulMe

#### What's this PR do?
Adds mobile footer
#### Where should the reviewer start?
At MobileFooter.vue
#### How should this be manually tested?
the component is placed on the components section
#### Any background context you want to provide?
The component appears on mobile screens only (576px or less), adds several buttons that can be pressed
#### What are the relevant tickets?
[#73](https://github.com/bitshares/bitshares-community-ui/issues/73)
#### Screenshots (if appropriate)
<img width="528" alt="screen shot 2018-10-21 at 11 03 21" src="https://user-images.githubusercontent.com/26275425/47264561-038d5b00-d522-11e8-9822-5f85fe6691d4.png">

#### URL
Provide a link to your deploy from http://staging-ui.trusty.apasia.tech:8080/
http://staging-ui.trusty.apasia.tech:8080/73-mobile-footer
#### Questions:
What can be improved?

2018-10-23 18:07 UTC, roma219 requested changes
Needs changes

Doesn't look like design:
![image](https://user-images.githubusercontent.com/4411295/47381068-a94def00-d707-11e8-82ad-e4845b675691.png)

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +      @itemClick="handleClick(index)"
what is `@itemClick` ?

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +      @itemClick="handleClick(index)"
Why so many emits?

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +        name="paste"
icon name should be gotten from item

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +      <div class="text">{{ item }}</div>
item should be an object with a structure `{ name, title, icon }`

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +@media (min-width: config('screens.sm')) {
No media queries - https://tailwindcss.com/docs/

2018-10-23 18:07 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +  width:33px;
no pixels

2018-10-23 21:37 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +  width:33px;
got it

2018-10-23 21:38 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +@media (min-width: config('screens.sm')) {
ok, it is better without `@media`

2018-10-23 21:38 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +      <div class="text">{{ item }}</div>
okay

2018-10-23 21:39 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +        name="paste"
as a property, ok

2018-10-23 21:39 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +      @itemClick="handleClick(index)"
will refactor

2018-10-23 22:06 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +@media (min-width: config('screens.sm')) {
though `@screen` only covers min-width

2018-10-23 22:09 UTC, MindfulMe commented on src/components/MobileFooter/MobileFooter.vue
> +@media (min-width: config('screens.sm')) {
I use multiple ranges <img width="254" alt="screen shot 2018-10-24 at 01 07 25" src="https://user-images.githubusercontent.com/26275425/47393807-381f3380-d729-11e8-9ae4-b5b7f9b1fa54.png">

2018-10-29 07:20 UTC, roma219 commented
Open when it looks & behaves like in design and ready for review

2018-10-30 00:08 UTC, MindfulMe commented
@roma219 
<img width="529" alt="screen shot 2018-10-30 at 02 07 46" src="https://user-images.githubusercontent.com/26275425/47687389-a9a72800-dbe8-11e8-83ae-c48f11c20cc9.png">

2018-10-30 07:02 UTC, roma219 requested changes
Needs changes, see comments

Also:
1) Should be no line-break
![image](https://user-images.githubusercontent.com/4411295/47701413-c19f9b80-dc2a-11e8-92f0-c98ad29c3f23.png)
2) Active tab text & icon colors should be primary
3) Still not quite like design...:
![image](https://user-images.githubusercontent.com/4411295/47701438-daa84c80-dc2a-11e8-9e95-0f6fea300737.png)
![image](https://user-images.githubusercontent.com/4411295/47701453-e09e2d80-dc2a-11e8-829a-2fc16b8278ab.png)
4) Use Markets, Orders and Account as test tabs w corresponding icons

2018-10-30 07:02 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +@media (max-width: config('screens.sm')) {
No need for media queries at all, use tailwind classes and responsive prefixes to hide footer on large screens
https://tailwindcss.com/docs/display
https://tailwindcss.com/docs/responsive-design

2018-10-30 07:02 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +      :class="activeIndex === index ? 'active' : ''"
better write it like this:
`:class="{'active': activeIndex === index }"`

2018-10-30 07:02 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +@media (max-width: config('screens.sm')) {
No need for media queries at all, use tailwind to hide it on large screens:
https://tailwindcss.com/docs/responsive-design
https://tailwindcss.com/docs/display

2018-10-30 21:39 UTC, MindfulMe commented
ok, now only need the icons

2018-10-30 22:47 UTC, MindfulMe commented
@roma219 should be ok, but though there is a small difference regarding a gap in the mockups 
<img width="179" alt="screen shot 2018-10-31 at 00 45 02" src="https://user-images.githubusercontent.com/26275425/47755321-85118580-dca6-11e8-91c9-9cfe9aecf241.png">
<img width="224" alt="screen shot 2018-10-31 at 00 44 54" src="https://user-images.githubusercontent.com/26275425/47755324-8773df80-dca6-11e8-8b33-ece13f0ca1df.png">

2018-10-31 06:33 UTC, roma219 requested changes
remove media querie

2018-10-31 06:33 UTC, roma219 commented on src/components/MobileFooter/MobileFooter.vue
> +@screen sm {
no media queries

2018-10-31 16:00 UTC, roma219 requested changes
Remove trailing comma and it's good to go

2018-10-31 16:00 UTC, roma219 commented on tailwind.js
> +    'xl': '1200px',
trailing comma

2018-10-31 16:10 UTC, MindfulMe commented on tailwind.js
> +    'xl': '1200px',
probably did not include in the commit

2018-10-31 16:10 UTC, MindfulMe commented on tailwind.js
> +    'xl': '1200px',
got it

2018-10-31 16:47 UTC, roma219 approved these changes

2018-10-31 16:47 UTC, merged